export const starterUnits=[
 {id:'useful',title:'What AI actually does',goal:'Recognize a useful draft without treating it as an authoritative fact.',terms:['Artificial Intelligence','Generative AI','ChatGPT','Large Language Model','Machine Learning'],note:'A language model learns patterns during training. In a conversation it uses those patterns and the supplied information to produce an answer; it does not automatically verify the answer against your business records.',question:'A supplier email is long and unclear. What useful first task could an assistant perform?',options:['Draft a source-linked summary for the buyer to check.','Use the email to update the authoritative delivery date immediately.','Replace the supplier record with a shorter version of the email.'],correct:0,why:'A summary can reduce reading effort while the buyer verifies what the supplier actually confirmed. Writing a clear answer does not make it authoritative.'},
 {id:'instructions',title:'Give the assistant enough information',goal:'Understand instructions, supporting facts, limits and uncertainty.',terms:['Prompt','Context','Token','Context Window','Hallucination'],note:'The same question can produce different wording or conclusions because generation is based on learned likelihoods, and settings or available context can differ. Even consistent answers can be wrong. Ask for missing information rather than invented facts.',question:'An assistant is asked to draft a proposal but receives no agreed scope. What should happen?',options:['Use a typical project scope to make the draft concrete.','Ask for the approved goal, scope, constraints and sources before committing details.','Write a polished proposal and leave review until pricing is finalized.'],correct:1,why:'Clear instructions cannot supply facts the client has not agreed. A useful draft must distinguish confirmed scope from questions still needing answers.'},
 {id:'data',title:'Separate data, rules and interpretation',goal:'Recognize where predictable fields and calculations are safer.',terms:['Structured Data','Unstructured Data','Structured Output','Deterministic Automation','Database'],note:'A form stores named facts; a database manages records; a formula calculates by rules. AI can help interpret variable language. These are complementary methods, not interchangeable tools. A JSON answer can have correct formatting and incorrect quantities.',question:'Project dimensions are approved and quantity formulas are fixed. Which design best fits?',options:['Use AI for the quantities and ask it to explain its calculation.','Ask employees to calculate everything manually so no automation is involved.','Use approved formulas for quantities and reviewed AI for unusual notes.'],correct:2,why:'Stable arithmetic belongs in tested rules. Variable notes may benefit from interpretation, with a human verifying meaningful exceptions.'},
 {id:'connections',title:'Connect software without assuming AI',goal:'Ask practical feasibility questions before recommending an integration.',terms:['Automation','API','Integration','Webhook'],note:'A rule-based workflow might start when a form is submitted, validate fields, create a record and notify an employee. No AI is necessary. An API is the controlled request interface; a webhook is an event notification. Both need approved access and error recovery.',question:'Staff copy customer details from a CRM into scheduling. What should you investigate first?',options:['Whether an existing connector or API supports the needed fields, permissions and stable customer ID.','Which language model can reproduce the customer details most accurately.','Whether replacing both applications would remove all integration effort.'],correct:0,why:'The issue may be a normal software connection. Confirm supported operations, identifiers, authority and exception handling before introducing AI or replacement software.'},
 {id:'agents',title:'Give an assistant bounded tools',goal:'Distinguish an answer, a tool request and an authorized business action.',terms:['AI Agent','Tool','Tool Calling','Human-in-the-loop','Guardrail','Least Privilege'],note:'An agent can choose steps and request tools. The application, not the model alone, must enforce permissions. Guardrails include input validation, restricted tools, approval and stopping rules. Never upload real sensitive records merely to try a training exercise.',question:'A supplier-status assistant needs approved messages. What permission should a first pilot use?',options:['Order-editing access so it can resolve any problem it discovers.','Read-only source access, reviewed recommendations and a stop/escalation route.','All supplier folders, with instructions to ignore confidential content.'],correct:1,why:'The task requires reading and interpretation, not procurement authority. Narrow permissions limit the consequences of model error or hostile document instructions.'},
 {id:'knowledge',title:'Answer from approved company information',goal:'Know when source retrieval helps and why review still matters.',terms:['Knowledge Base','RAG','Embedding','Semantic Search'],note:'A knowledge base contains approved information. Retrieval finds relevant passages; embeddings help compare meaning so differently worded questions can find related text. RAG supplies retrieved passages to the model before it drafts an answer. Check source currency, permission, relevance and whether the answer is actually supported.',question:'An owner wants an assistant to answer from changing company policies. What would you validate?',options:['Whether a longer prompt can fit every policy indefinitely.','Whether additional model training means policies need no version checks.','Whether approved current sources can be retrieved, cited and checked for representative questions.'],correct:2,why:'Source-based answering can fit changing facts better than relying only on general model knowledge. Retrieval and citations must be evaluated; they do not guarantee a correct interpretation.'}
];
export const mixedSteps=[
 ['Capture project details','system','A form stores approved project ID, revision and required inputs.','Structured data collection is software, not AI.'],
 ['Validate required fields','rules','Reject missing revision, date or equipment type using explicit conditions.','Stable validation belongs in deterministic rules.'],
 ['Notify the request owner','automation','A valid submission automatically triggers an owned notification.','Automatic execution does not require language interpretation.'],
 ['Interpret unusual supplier notes','ai','Propose a source-linked explanation of ambiguous wording.','AI assistance helps with language; the proposed interpretation remains reviewable.'],
 ['Resolve incompatible materials','human','A qualified reviewer investigates compatibility with the approved layout.','Expert judgment and accountability stay with the qualified person.'],
 ['Authorize purchase release','approval','An authorized buyer permits a reviewed current order to be released.','Approval is a distinct authority boundary, not merely another calculation.'],
 ['Decide a consequential substitution','ai-decision','An owner proposes delegating material choice to a model. Identify the AI-decision boundary and retain qualified approval.','Recognizing an AI decision does not mean approving it: this consequential delegation is unsuitable without justified authority and validated controls.']
];
export const typeLegend=[['human','Human','Judgment and accountable work'],['rules','Deterministic rules','Specified calculations and validation'],['automation','Automation','Automatic execution of a defined route'],['ai','AI-assisted','Interpretation or drafting for review'],['ai-decision','AI decision','A model determines a consequential outcome'],['system','System / database','Store and coordinate authoritative records'],['approval','Human approval','Permission before a binding action']];
export const ownerConversations=[
 ['We need AI.','What measurable result do you want to improve? Let us trace recent work before choosing technology.','Choose an assistant first so the discovery discussion has a concrete product.','The client states a tool preference, not an established business cause.'],
 ['I want a chatbot.','Which questions, sources, volumes and escalation needs should it handle? We can compare a bot with clearer forms or FAQs.','Build a general bot, then use the questions it receives to discover the requirements.','Unbounded pilots can expose data and create misleading expectations.'],
 ['Can we automate everything?','Some steps suit rules; ambiguous or consequential decisions may need a person. We will define a mixed workflow with exceptions.','Aim for full automation and add review only where the prototype fails.','Authority and failure cost must be designed before consequential actions.'],
 ['Can AI replace this employee?','Let us assess tasks, quality, demand and redeployment. A pilot can measure capacity; staffing decisions need management and HR review.','Estimate role replacement from the fraction of routine tasks in the job description.','Task savings do not establish that an entire role or expenditure disappears.'],
 ['Can ChatGPT connect to our software?','That depends on approved capabilities, connectors or APIs, permissions and the exact actions needed. A chat alone does not prove access.','If it can understand the task, connecting it should be a routine configuration step.','Language capability does not establish integration feasibility or authority.'],
 ["Why can't we upload all our company documents?",'We need approved sources, necessary data, access and retention rules. Legal, IT or other specialists may need to review sensitive material.','Remove employee names and upload the remaining folders to avoid blocking the pilot.','Removing names does not remove trade secrets, sensitive details or access obligations.'],
 ['Why does this need human approval?','This step commits money or affects compatibility. We can simplify review, but authority must remain explicit before the action.','Keep approval during the pilot and remove it once the model usually agrees with reviewers.','Agreement frequency alone does not justify transferring purchase authority.'],
 ['Why is this solution so expensive?','The scope includes discovery, validation, exceptions, testing, training and support. We can compare a smaller pilot and simpler alternatives.','Emphasize the advanced technology and its potential for future features.','Price should be explained through agreed scope, risk and business value.'],
 ["Why don't we just build an agent?",'An agent is useful when variable planning adds value. For stable fields and calculations, a controlled workflow can be easier to test and maintain.','An agent provides flexibility, so it is the safest way to avoid redesign later.','Flexibility introduces tool, permission and recovery complexity that needs justification.'],
 ['What happens when AI is wrong?','We will define source checks, risk-based review, exception ownership and a safe fallback, then test representative failures.','Use the strongest model and ask it to check its own answer before release.','Self-checking can help but does not provide independent factual authority.'],
 ['Is our data safe?','We must review the information, recipients, permissions, storage, retention and vendor practices with your responsible specialists. I cannot guarantee safety from a feature label.','Use a provider offering encryption and describe the workflow as secure.','Encryption alone does not establish appropriate access or use.']
];
export const toolCategories=[
 ['General AI assistant','Reviewed drafting, interpretation and exploration','A staff member needs a draft summary.','Stable calculations or unapproved sensitive information.','What sources, review and data policy are required?'],
 ['Automation platform','Connect defined events, rules and actions','A valid request creates a record and notification.','Unclear identifiers or an unowned exception route.','Which operations, retries and monitoring are supported?'],
 ['Forms and spreadsheets','Collect consistent facts and perform controlled calculations','A small team needs validated intake and shared quantity rules.','Complex access, concurrency or record-integrity requirements beyond the tool.','Who owns field definitions, formula versions and permissions?'],
 ['Database and business systems','Manage authoritative records and owned statuses','Customers, projects or invoices need stable IDs.','Adding storage without solving unclear ownership.','Can the existing CRM or workflow system meet the need?'],
 ['Document tools and knowledge bases','Organize current approved source material','Staff need a searchable procedure library.','Uncontrolled versions or documents nobody owns.','Who approves, updates and restricts each source?'],
 ['AI model APIs and agent frameworks','Embed model capabilities and bounded tools into an application','A validated interpretation task needs integration and observability.','A simple form or fixed rule already meets the objective.','Who will build, enforce permissions, evaluate and support it?'],
 ['Dashboards and workflow systems','Show outcomes, queues and exceptions','An owner needs baseline/pilot and overdue-work visibility.','Reporting a metric that does not support a business decision.','Which source, owner and decision does each measure support?']
];
export const lessonBridges={fit:['Generative AI','Deterministic Automation','Structured Data'],reliability:['Large Language Model','Context','Structured Output','JSON','Prompt Injection','API','Webhook'],discovery:['Trigger','Source of Truth','Exception'],diagnosis:['Bottleneck','Root Cause','Rework'],current:['Workflow','Branch','Record'],future:['Business Rule','Approval Gate','Idempotency'],value:['ROI','Operating Cost','Data Quality'],delivery:['Prototype','Pilot','Production','Monitoring']};
export const lessonVisuals={
 fit:{title:'One workflow. Different kinds of work.',caption:'Choose a method for each step; adding AI to one step does not make the whole process autonomous.',steps:[['system','Collect approved facts'],['rules','Calculate quantities'],['ai','Interpret unusual notes'],['approval','Authorize release']]},
 reliability:{title:'A well-formed answer still needs evidence',caption:'Field format, source accuracy and authority are three different checks.',steps:[['system','Invoice source'],['ai','Propose fields'],['rules','Validate format and match'],['human','Review uncertain facts'],['approval','Authorize payment']]},
 discovery:{title:'Follow a real transaction',caption:'Listen for the difference between the owner’s goal and the employee’s actual handoffs.',steps:[['human','Ask for a recent example'],['system','Inspect source records'],['human','Trace owners and waiting'],['rules','Separate estimate from measurement']]},
 diagnosis:{title:'Minutes of typing. Days of waiting.',caption:'Example: 5 minutes entry + 2 minutes review + 3 days in a queue. Speeding entry cannot remove the dominant delay.',steps:[['system','Request arrives'],['human','5 min entry'],['approval','3-day approval queue'],['human','2 min review'],['system','Order proceeds']]},
 current:{title:'Show the exception, not just the happy path',caption:'An incomplete request returns to an owner. It does not disappear between the normal steps.',steps:[['system','Request'],['human','Coordinator entry'],['decision','Complete? Yes → dispatch; no → intake owner'],['system','Service and billing'],['human','Missing address → intake owner']]},
 future:{title:'Approval belongs to a specific revision',caption:'Revision B invalidates the earlier calculation and approval. Recalculate and review before release.',steps:[['system','Revision B received'],['rules','Validate current inputs'],['rules','Recalculate approved formulas'],['approval','Reapprove current BOM'],['automation','Release one authorized order']]},
 value:{title:'Value does not cancel a critical risk',caption:'High potential benefit is a reason to investigate, not permission to skip data or authority checks.',steps:[['system','Measure frequency and effort'],['rules','Estimate realized net value'],['human','Check data and exceptions'],['approval','Resolve risk gate'],['automation','Bounded pilot']]},
 delivery:{title:'A pilot earns permission to expand',caption:'A prototype demonstrates possibility; a pilot tests representative work, adoption and exceptions.',steps:[['human','Discover and document'],['system','Design and prototype'],['rules','Test acceptance'],['approval','Approve bounded release'],['human','Train, measure, improve']]}
};
