// Provider contract: async reply({ message, route }) -> { text, provider }.
// Future API providers belong behind a local server endpoint; credentials never enter browser code.
export const localMentor = {
  async reply({message}) {
    const s=message.toLowerCase();
    const text=/roi|cost|saving|payback/.test(s)?'Separate capacity from cash savings. What is your measured volume, current time, future time including review, loaded hourly cost and ongoing support cost? Try a downside case with 50% realization. What evidence supports your assumptions?':/agent|autonomous/.test(s)?'First explain what decisions need flexible planning. If a form and rules solve the problem, keep them. For a bounded agent, define role, objective, inputs, read-only tools, forbidden actions, human approval, output and stop conditions. Who owns recovery?':/privacy|risk|security|data/.test(s)?'List the exact data needed and who may access it. Use fictional or redacted pilot records. Consider retention, vendor approval, prompt injection and least privilege. Which legal, IT or domain reviewer must approve before production?':/map|workflow|process/.test(s)?'Follow one recent transaction: trigger, inputs, owners, systems, handoffs, waiting and output. What happens if required information is missing? Keep the current state separate from your proposed design. Where does the actual bottleneck sit?':/client|interview|discovery/.test(s)?'Ask the owner what success looks like, then ask an employee to show a recent transaction. Follow up on systems, timing, duplicate entry and exceptions. Which claim is still an estimate? Open a client engagement to practice with predefined stakeholder answers.':/api|webhook|token|llm|rag/.test(s)?'Look up the term in the glossary, then connect it to a business decision. For every integration, identify data ownership, permissions, a unique ID and a failure path. How will you verify a result before it causes a binding action?':'State the business goal, current process and observed pain. What evidence identifies the root cause? Compare a process change, ordinary software, rules and AI. Choose the simplest reliable improvement, then define a pilot and measurement.';
    return {text,provider:'Local mentor · predefined guidance'};
  }
};
