// Plain-language reference content. Each entry is authored around a business use.
const groups={
'AI fundamentals':`
Artificial Intelligence|Software that performs tasks associated with interpretation, prediction or judgment.|A system proposes a category for a customer request.|Ask which specific task improves, and how accuracy will be checked.|Model,Automation
Generative AI|AI that creates a draft of text, images, audio or other content from instructions and context.|An assistant drafts a proposal from approved discovery notes.|Treat generated material as a draft requiring appropriate verification.|Large Language Model,Hallucination
Machine Learning|Methods that learn patterns from examples rather than listing every rule by hand.|A model learns patterns associated with late deliveries.|Check whether representative examples exist before promising useful predictions.|Training,Data Quality
Large Language Model|A model trained on large collections of language that generates or interprets text using patterns and context.|An assistant turns a long supplier email into a draft status summary.|It can help with language but does not become an authoritative database.|LLM,Context,Hallucination
LLM|The abbreviation for large language model: a system that generates likely language from instructions and context.|A coordinator uses an LLM to draft a customer response.|Verify important facts against approved sources rather than confident wording.|Large Language Model,Prompt
Foundation Model|A broadly trained model that can be adapted or instructed for many tasks.|The same underlying model can summarize notes or classify emails.|Broad capability does not prove suitability for a particular client workflow.|Model,Fine-tuning
Model|The trained system that turns an input into a prediction or generated output.|An invoice model proposes vendor and amount fields.|Choose using representative performance, risk and cost, not an impressive demo.|Inference,Training
Inference|Running a trained model on a new input to obtain an output.|An assistant processes today's supplier update.|Account for runtime cost, delay and failure handling in the business case.|Model,Latency
Training|Adjusting a model using examples so it learns patterns.|A developer trains a model on labeled document categories.|Training is different from attaching documents to one request.|Fine-tuning,Context
Fine-tuning|Further training an existing model with selected examples to change its behavior.|A specialist tunes consistent labeling of industry-specific requests.|It is not automatically the right way to supply changing company facts.|Training,RAG
Prompt|Instructions or a question given to an AI system.|Summarize this approved update and list missing delivery information.|Specify the task, source boundary and expected output.|User Prompt,Context
System Prompt|Higher-level instructions that define an assistant's role and behavior.|An assistant is instructed to flag uncertainty and never authorize purchases.|Instructions supplement permissions and validation; they are not security enforcement alone.|Guardrail,Permission
User Prompt|The task-specific instruction a person sends to an assistant.|Draft a nonbinding reply to this fictional vendor email.|Teach staff to include purpose, relevant facts and review expectations.|Prompt,System Prompt
Context|Information available to the model while it handles a task.|A buyer includes the current revision and an approved supplier message.|Missing or conflicting context can produce a plausible but wrong answer.|Context Window,Source of Truth
Context Window|The amount of input and output a model can handle in one request.|A large manual may exceed the space available for one answer.|Plan which information is relevant instead of assuming unlimited recall.|Token,RAG
Token|A small chunk of text or other encoded input/output used in model processing.|A long document and a long answer consume more tokens than a short exchange.|Tokens affect capacity and often cost; they are not always whole words.|Context Window,Operating Cost
Temperature|A generation setting that can influence variation in model outputs.|A drafting task may allow more varied wording than a fixed classification task.|Less variation does not guarantee factual accuracy.|Hallucination,Structured Output
Hallucination|An output that states unsupported or false information as if it were factual.|An assistant invents a supplier delivery date absent from the email.|Build source checks and exception routes before anyone acts on important facts.|Grounding,Human-in-the-loop
Multimodal AI|AI that can work with more than one kind of input, such as text and images.|An assistant interprets a photographed invoice and its accompanying email.|Test legibility and document variety; accepting an image does not prove correct reading.|OCR,Document Extraction
Structured Output|An answer arranged in defined fields or a specified format.|An extractor returns invoice number, vendor and amount separately.|Check both field format and factual support; valid structure can contain wrong facts.|Schema,JSON
Natural Language Processing|Software methods for interpreting or generating ordinary human language.|A system groups differently worded support requests by topic.|Use it where language variation is a real constraint, not for stable arithmetic.|Classification,LLM
Reasoning Model|A model designed to spend more processing on multi-step problems.|A model analyzes a proposed plan for contradictory requirements.|Compare practical quality, latency and cost; extra processing does not confer authority.|Model,Latency
ChatGPT|A conversational AI application people use to ask questions and create or analyze content.|An employee drafts an outline from fictional training notes.|Using an assistant manually is different from connecting it to business systems.|Prompt,API,AI Agent
Probabilistic AI|A system whose outputs are based on learned likelihoods and can be uncertain.|Similar customer emails may receive different proposed classifications.|Measure errors and define review rather than expecting fixed-rule certainty.|Deterministic Automation,Model Risk
`,
'Automation':`
Automation|Software carrying out defined work without a person repeating each action.|A completed intake form creates a request record and notification.|Automation can use ordinary rules without any AI.|Trigger,Action,Deterministic Automation
Workflow|The sequence of work, decisions and handoffs that produces a business result.|A purchase request moves through review, order release and delivery tracking.|Understand the process before choosing technology.|Trigger,Process Mapping
Trigger|The event or condition that starts work.|Submitting a service form starts intake.|Define what starts a transaction so it is not processed twice.|Webhook,Event-Driven Automation
Action|A step performed after a trigger or decision.|Create a draft job record from validated fields.|Clarify side effects and who is authorized to perform them.|Trigger,Tool
Condition|A test that determines which path work follows.|A request missing an address is sent back for clarification.|Use explicit tests for stable business boundaries.|Branch,Business Rule
Branch|One of the possible paths through a workflow.|Urgent requests take an escalation path instead of the normal queue.|Map exceptions as well as the usual route.|Condition,Exception
Rule|An explicit instruction for consistent behavior.|Send an alert when a confirmed delivery becomes overdue.|Use rules when the desired behavior can be specified reliably.|Business Rule,Deterministic Automation
Business Rule|An explicit policy or calculation governing work.|Orders above an approved limit need buyer authorization.|Ask who owns, validates and changes the rule.|Approval Gate,Source of Truth
Deterministic Automation|Execution that follows specified rules and produces the same result from the same valid inputs.|Approved formulas calculate solar material quantities.|Prefer controlled calculations for stable quantities and binding business rules.|Probabilistic AI,Business Rule
Scheduled Automation|Work that runs at planned times.|A daily report lists overdue purchase orders.|Choose a schedule that fits the response target and monitoring needs.|Trigger,Monitoring
Event-Driven Automation|Work that runs when a relevant event occurs.|A supplier status change initiates a delivery notification.|Expect duplicate or delayed events and plan recovery.|Webhook,Retry
Human-in-the-loop|A person participates at a defined review or decision point.|A buyer verifies an uncertain supplier substitution.|Specify what is reviewed, by whom, and what happens on rejection.|Approval Gate,Escalation
Exception|A situation the normal path cannot safely handle.|A project lacks a required racking family.|Assign an owner and visible status instead of silently guessing.|Fallback,Escalation
Fallback|An approved alternative route when the main route cannot operate.|A buyer verifies order state and uses a manual ordering route during an outage.|A fallback must avoid repeating an already completed transaction.|Exception,Idempotency
Retry|Another attempt after a failed or uncertain operation.|A connector repeats a request after a timeout.|Bound retries and verify transaction identity to prevent duplicate side effects.|Idempotency,Rate Limit
Approval Gate|A point where an authorized person or policy must permit progression.|A reviewed bill of materials waits for authorized purchase release.|Approval belongs before the binding action and should match the current revision.|Permission,Human-in-the-loop
Webhook|An event message one system sends to another at a configured address.|A scheduling system notifies billing when a job is completed.|Validate the sender and handle repeated deliveries safely.|Endpoint,Event-Driven Automation
Idempotency|Design that prevents repeating the same request from creating another business effect.|The same job event received three times still creates one job.|It is essential when retries can place orders or create records.|Retry,Record
`,
'Agents':`
AI Agent|An AI-assisted system that can choose steps and use permitted tools toward a goal.|An assistant looks up supplier updates and proposes a status summary.|Define objective, tools, stop conditions and approval before granting autonomy.|Tool Calling,Guardrail
Agent|A short name for an AI system that can plan steps and use allowed tools.|A supplier assistant retrieves approved updates before drafting a summary.|A conversational answer alone does not imply safe independent action.|AI Agent,Autonomy
Agentic Workflow|A workflow where AI chooses some steps or tool use within boundaries.|An assistant chooses which approved document to retrieve for a question.|Use adaptive planning only where it adds measurable value over fixed routing.|AI Agent,Orchestration
Tool|A capability a system may invoke to read information or perform an action.|A permitted lookup returns the current delivery status.|Separate read-only capabilities from actions that change business records.|Permission,Tool Calling
Tool Calling|A model requesting a defined capability through a controlled interface.|An assistant asks for a supplier-status lookup.|The application must enforce permissions and validate arguments.|Tool,Function Calling
Function Calling|A tool-call pattern using named functions and defined inputs.|A system requests lookupOrder with a validated order ID.|A function's schema does not establish permission or factual correctness.|Tool Calling,Schema
Memory|Information retained to support later work.|An assistant retains a reviewed project preference.|Distinguish temporary context from stored records, access and retention.|Persistent Memory,Context
Short-Term Context|Information available during the current exchange or task.|The current supplier message stays available while drafting a reply.|Do not assume it will persist across later tasks.|Context,Memory
Persistent Memory|Information stored for later sessions or tasks.|A workflow stores a client's approved communication preferences.|Require ownership, correction, access and retention controls.|Database,Data Retention
Orchestration|Coordinating tasks, tools and handoffs.|A workflow routes extracted invoice fields to validation and review.|Simple fixed sequencing may be easier to operate than adaptive planning.|Workflow,Agentic Workflow
Planning|Choosing a sequence of steps to achieve an objective.|An assistant decides to retrieve a source before answering.|Review the plan's authority and stop conditions, not just its plausibility.|Agent Loop,Guardrail
Guardrail|A control that limits behavior or detects unsafe outputs.|A system blocks purchase release if approval is absent.|Use enforced permissions, validation and monitoring alongside instructions.|Approval Gate,Access Control
Agent Loop|Repeated cycles of planning, tool use and checking results.|A status assistant retrieves a document, checks gaps and asks for clarification.|Set step, time and cost limits and a clear escalation route.|Planning,Retry
Multi-Agent System|Several agents coordinating separate roles or tasks.|Different assistants propose research and review drafts.|Extra handoffs increase complexity; justify them against a simpler workflow.|Orchestration,Implementation Cost
Autonomy|The extent to which a system can act without asking a person.|An assistant may draft a message but cannot send a purchase commitment.|Grant only the independence justified by the task and risk.|Permission,Approval Gate
Permission|Authorization to access information or perform an action.|A tool may read an order but cannot change its quantity.|Enforce permission in software, not only in a prompt.|Least Privilege,Access Control
Escalation|Routing a problem to someone with the required authority or expertise.|A conflicting layout goes to a qualified material reviewer.|Specify the trigger, owner and response target.|Exception,Human-in-the-loop
`,
'Data':`
Structured Data|Information arranged in predictable named fields.|A request form records project ID, date and equipment type separately.|It is easier to validate and transfer than ambiguous notes.|Field,Schema
Unstructured Data|Information without a fixed field layout.|A supplier describes a delay in an email paragraph.|AI may help interpret it, but important facts still need verification.|Document Extraction,Structured Data
Semi-Structured Data|Information with some recognizable labels but variable contents or layout.|Emails share subject and sender fields while message bodies vary.|Determine which parts can be handled by rules and which need interpretation.|Schema,Unstructured Data
Database|An organized store designed to retrieve and manage records.|A service database stores customers and jobs by stable IDs.|It is a storage and coordination tool, not automatically AI.|Table,Record
Spreadsheet|A grid of cells used for calculations and small-scale data work.|A shared Sheet calculates reviewed material quantities.|Check access, formula control and scale before replacing a simple useful tool.|Database,Business Rule
Table|A collection of similarly structured records.|An orders table has one row per purchase order.|Consistent fields and IDs support reliable connections.|Record,Field
Record|One stored item describing a business entity or transaction.|One row represents purchase order PS-204.|Establish a stable identifier to prevent mistaken matches and duplicates.|Table,Source of Truth
Field|A named piece of information in a record.|The deliveryDate field contains the required date.|Specify type, required status and authority for important inputs.|Schema,Data Validation
Schema|A definition of how data is organized and what formats fields accept.|Invoice output requires a number for amount and text for vendor ID.|Format validation does not prove the extracted facts match the source.|Structured Output,JSON
JSON|A text format for named values, lists and nested data.|An integration sends project ID and validated quantities as JSON.|Readable structure helps transfer data, but does not verify its business meaning.|Payload,Schema
CSV|A text table with rows and separated values.|An accountant exports invoice records for analysis.|Check separators, dates, identifiers and formatting during transfer.|Table,Spreadsheet
Data Validation|Checking that input satisfies required format and business conditions.|A form rejects a missing revision or a negative quantity.|Validate before downstream work depends on unreliable inputs.|Business Rule,Data Quality
Data Quality|How fit information is for the intended use, including accuracy and completeness.|A customer table has duplicate names and missing addresses.|Poor data can make a technically functioning automation ineffective.|Data Validation,Source of Truth
Data Pipeline|A sequence that collects, transforms and moves information.|Approved job details flow into billing and a reporting table.|Map ownership, transformations and error recovery at each stage.|Data Source,Integration
Data Source|The place information originates.|An approved engineering layout supplies equipment requirements.|Ask whether the source is current, authoritative and permitted.|Source of Truth,Grounding
Source of Truth|The approved authoritative record for a particular fact.|The current approved layout defines the project revision.|Resolve conflicts by authority and version, not confident wording or recency alone.|Data Source,Record
System of Record|The designated system holding the authoritative business record for a particular purpose.|Approved orders live in the purchasing system even if staff view copies in Sheets.|Agree which system owns updates before connecting or synchronizing tools.|Source of Truth,Integration
Stable Identifier|A consistent unique label used to refer to the same item across steps or systems.|A job ID links intake, dispatch and billing.|Match by identity rather than similar customer names or AI guesses.|Record,Idempotency
Revision|A particular version of a specification, document or record.|Layout revision B replaces the earlier approved layout.|Tie calculations and approval to the exact version reviewed.|Source of Truth,Approval Gate
Data Mapping|Defining how fields in one system correspond to fields in another.|A scheduling customer ID maps to the accounting customer record.|Validate meaning, format and identity before connecting systems.|Field,Integration
`,
'APIs & integrations':`
API|A controlled way for software to request information or an action from another system.|Scheduling asks accounting whether an invoice has been paid.|API availability, permissions and supported operations determine connection feasibility.|Integration,Endpoint,Authentication
REST API|A common style of API using web requests to work with resources.|A scheduling application requests an order record at a defined address.|Ask which operations and limits the specific API supports.|HTTP,Endpoint
Endpoint|A particular address where an API accepts a request.|An order-status endpoint returns information for a given order ID.|An endpoint's existence does not mean it supports every needed action.|API,Request
Request|A message asking a system for information or an operation.|A connector asks for the status of purchase order PS-204.|Validate inputs, permission and whether the request can create side effects.|Response,Payload
Response|The result a system returns after a request.|Accounting returns a payment status or an error.|Define what each result means and how errors are handled.|Request,Status Code
Authentication|Checking the identity of whoever requests access.|A connector proves it is the approved billing integration.|Authentication does not itself grant every permission.|OAuth,Access Control
API Key|A secret credential used by some APIs to identify or authorize a caller.|A backend connector uses an approved service credential.|Keep credentials out of client pages, shared notes and source code.|Authentication,Least Privilege
OAuth|An authorization method allowing an application approved access without sharing a user's password.|An employee authorizes a connector to read selected calendar information.|Review scope, expiry and revocation with appropriate IT support.|Authentication,Permission
Rate Limit|A restriction on how many requests a service accepts over a period.|A connector delays work after reaching an allowed request count.|Design queues, bounded retries and workload estimates.|Retry,Operating Cost
Integration|A connection that coordinates information or actions between systems.|A completed service job creates a billing draft.|Agree identifiers, field mappings, authority and exception recovery.|API,Connector
Connector|A packaged adapter for linking a particular application to a workflow.|An automation platform offers a scheduling connector.|Check supported operations rather than assuming the product name implies full coverage.|Integration,API
Middleware|Software between systems that routes or transforms their exchanges.|A small service translates job fields into billing fields.|It can solve compatibility gaps but adds maintenance and ownership.|Integration,Data Pipeline
HTTP|The request-and-response protocol commonly used by web services.|A connector makes an HTTP request to a billing API.|Understand success, errors and timeouts at a practical level.|GET,POST,Status Code
GET|An HTTP method commonly used to retrieve information.|A system retrieves an order's current status.|Use read operations for lookup tasks and follow the provider's contract.|HTTP,Request
POST|An HTTP method commonly used to submit data or create an operation.|A connector submits a new intake record.|Determine side effects and duplicate protection before retrying.|HTTP,Idempotency
Payload|The actual data carried in a message.|A request carries project ID, revision and delivery date.|Send only necessary validated information.|JSON,Request
Status Code|A code reporting the broad outcome of a web request.|A service reports success, missing records or a rate-limit error.|Codes inform recovery, but a lost response may leave transaction state uncertain.|Response,Retry
SDK|A software toolkit that helps developers use a service.|A developer uses helper functions to call an approved API.|An SDK can simplify implementation but does not replace security or business design.|API,Dependency
`,
'Knowledge systems':`
RAG|A method that retrieves relevant approved information before asking AI to draft an answer.|A company assistant retrieves a policy passage before answering a staff question.|Use it for source-based answers; still check relevance, authority and citations.|Retrieval-Augmented Generation,Grounding
Retrieval-Augmented Generation|The full name for retrieving information and using it to support a generated answer.|An assistant reads selected handbook passages instead of relying only on general knowledge.|Retrieval does not automatically make a model's interpretation correct.|RAG,Retrieval
Embedding|A numerical representation designed to help compare meaning or similarity.|Different descriptions of delivery delays can be matched to related notes.|Similarity supports search; it does not prove two records refer to the same transaction.|Vector,Semantic Search
Vector|An ordered collection of numbers; in AI search it can represent information for comparison.|A document's meaning is represented as an embedding vector.|You need to understand its purpose, not the underlying mathematics, to scope search.|Embedding,Vector Database
Vector Database|A store optimized for finding similar numerical representations.|A knowledge assistant searches stored document embeddings.|It is a retrieval building block, not an authoritative answer engine by itself.|Embedding,RAG
Semantic Search|Finding information by meaning rather than only matching exact words.|A query about late shipments finds documents mentioning delivery delays.|Evaluate whether matches actually answer the business question.|Embedding,Retrieval
Knowledge Base|An organized collection of information people or software can consult.|Approved procedures and FAQ articles form a support knowledge base.|Assign document ownership, currency and access before building an assistant.|RAG,Source of Truth
Document Chunk|A smaller part of a document prepared for retrieval.|A handbook is split into passages with source and version information.|Splitting must preserve enough context to avoid misleading answers.|Retrieval,Citation
Retrieval|Finding relevant information for a question or task.|A system fetches the current returns policy.|Evaluate whether the retrieved source is correct and authorized.|RAG,Semantic Search
Grounding|Tying an answer to supplied or retrieved evidence.|An assistant answers using a current approved policy passage.|A grounded answer can still misinterpret the source and needs suitable review.|Citation,Hallucination
Citation|A reference showing the source supporting a statement.|An assistant links to the policy passage behind its proposed answer.|Verify that the source exists and actually supports the claim.|Grounding,Source of Truth
`,
'Business systems':`
CRM|Software for managing customer, lead and relationship information.|Sales staff store prospect contacts and follow-up status.|Check whether it already supports the required workflow before adding tools.|Integration,Record
ERP|Software coordinating core business records such as purchasing, inventory and finance.|A manufacturer tracks approved orders and stock in an ERP.|Integration and authority boundaries matter more than adding AI features.|Inventory Management System,Accounting System
CMS|Software for managing published content.|A business maintains approved service pages in a CMS.|Confirm editing permissions and approval before automating publication.|Document Management System,Permission
SaaS|Software provided as an ongoing service, usually through a network.|A business subscribes to an online scheduling system.|Evaluate ongoing costs, access controls, vendor terms and exportability.|Vendor Risk,Operating Cost
POS|A point-of-sale system for recording sales transactions.|A restaurant records orders and payments at checkout.|Check transaction data and integration feasibility for reporting or inventory work.|Record,Inventory Management System
HRIS|Software managing employee and HR records.|An office tracks staff onboarding and employment details.|HR information needs appropriate permission and specialist review.|Sensitive Data,Access Control
Ticketing System|Software that records, assigns and tracks requests.|Support requests move through triage, escalation and resolution.|Use existing status and ownership features before inventing another queue.|Workflow,Escalation
Project Management System|Software coordinating tasks, responsibilities and project status.|A solar team tracks layout approval and installation readiness.|Confirm the system can supply current approved project facts.|Source of Truth,Integration
Accounting System|Software recording financial transactions and balances.|Bookkeepers review invoices and reconcile payments.|Retain appropriate financial authority and auditability when connecting it.|Approval Gate,Audit Log
Inventory Management System|Software tracking stock quantities, locations and movements.|A restaurant tracks units consumed and received.|Reliable units and stock data must precede useful purchase forecasting.|Data Quality,Business Rule
Document Management System|Software organizing documents, versions and access.|Approved layouts are stored with controlled revisions.|Ensure an assistant retrieves permitted current documents rather than outdated copies.|Data Retention,Source of Truth
`,
'Document processing':`
OCR|Software that converts visible text in an image into machine-readable text.|A scanned invoice becomes searchable text.|Poor image quality can introduce errors that require checking.|Document Extraction,Multimodal AI
Document Extraction|Turning document content into specified fields.|An invoice supplies proposed vendor, amount and invoice ID.|Measure field accuracy and review effort across realistic document types.|Structured Output,OCR
Classification|Assigning an item to a category.|A support email is proposed as billing, scheduling or urgent service.|Define categories, exception routing and the cost of misclassification.|Natural Language Processing,Escalation
Summarization|Producing a shorter account of source information.|An assistant drafts a meeting summary with actions.|Check omitted qualifications, decisions and source support.|Hallucination,Grounding
Entity Extraction|Identifying particular items such as names, dates or identifiers in text.|A system finds a PO number in a supplier message.|Validate identifiers before matching or changing records.|Document Extraction,Data Validation
Transcription|Turning speech or other recorded material into written text.|A recorded discovery interview becomes a draft transcript.|Obtain appropriate permission and check names, numbers and missing speech.|Speech-to-Text,Sensitive Data
Speech-to-Text|Converting spoken audio into text.|A voicemail becomes a draft service-request note.|Check addresses and urgent details before downstream action.|Transcription,Human-in-the-loop
Text-to-Speech|Converting written text into spoken audio.|An approved job instruction is read aloud.|Consider accessibility, privacy and whether wording is accurate before playback.|Multimodal AI,Access Control
`,
'Security & governance':`
Personally Identifiable Information|Information that can identify or be linked to a person.|A service record contains a customer's name and address.|Minimize exposure and obtain appropriate organizational review.|PII,Sensitive Data
PII|A common abbreviation for personally identifiable information.|A contact table contains names, phone numbers and addresses.|Removing one field may not prevent re-identification.|Personally Identifiable Information,Data Leakage
Sensitive Data|Information needing extra protection because misuse could cause harm.|Employee health or bank details require restricted handling.|Ask the appropriate specialist about obligations and approved processing.|Access Control,Compliance
Confidential Data|Information the business restricts even if it is not personal.|Supplier pricing and proprietary layouts are confidential.|Do not treat nonpersonal information as automatically safe to upload.|Data Leakage,Permission
Encryption|Protecting information by encoding it so authorized access is required to read it.|A service protects stored documents and network transfers.|Encryption supports protection but does not fix excessive authorized access.|Access Control,Vendor Risk
Access Control|Rules and enforcement determining who may read or change information.|Only authorized buyers can release purchase orders.|Map access to the actual task and business authority.|Permission,Least Privilege
Role-Based Access Control|Assigning permissions according to a defined role.|A reviewer can inspect materials while a buyer can authorize release.|Verify roles fit real responsibilities and exceptions.|Access Control,Permission
Least Privilege|Giving only the access necessary for the task.|A supplier-summary assistant reads updates but cannot alter orders.|Narrow access reduces the consequences of errors or misuse.|Permission,Guardrail
Audit Log|A record of important access, changes or decisions.|A log identifies who approved an order and which revision was used.|Logs support investigation and accountability when something fails.|Logging,Approval Gate
Data Retention|Rules for how long information is stored and when it is removed.|The business sets a reviewed retention period for interview notes.|Agree ownership and applicable requirements rather than keeping everything forever.|Compliance,Persistent Memory
Compliance|Meeting applicable rules, obligations and organizational requirements.|A clinic seeks specialist review before changing how patient information is processed.|Recognize when legal, IT, HR or other qualified review is required.|Sensitive Data,Vendor Risk
Prompt Injection|Untrusted content attempting to redirect an assistant's instructions or tool use.|A supplier PDF tells an assistant to export customer records.|Treat source text as data and enforce permissions outside the model.|Guardrail,Tool Calling
Data Leakage|Information reaching someone or somewhere without proper authorization.|An assistant includes confidential pricing in an external draft.|Control sources, recipients, tool access and review.|Confidential Data,Access Control
Model Risk|The potential harm from unsuitable, inaccurate or unreliable model behavior.|A confident wrong invoice amount causes financial rework.|Evaluate realistic failures and control consequential outputs.|Hallucination,Human-in-the-loop
Vendor Risk|Exposure arising from dependence on an external provider.|A connector provider changes availability, permissions or retention terms.|Review reliability, data practices, costs and exit options.|SaaS,Fallback
`,
'Business value & delivery':`
Use Case|A specific task or business situation a solution is meant to improve.|Reduce repeated entry between dispatch and billing.|Define an outcome instead of a broad request to use AI.|Pain Point,Success Metric
Pain Point|A recurring problem that costs effort or causes frustration.|Buyers repeatedly chase missing delivery dates.|Measure its effect and investigate the cause.|Root Cause,Bottleneck
Bottleneck|The constraint most limiting the desired process outcome.|Quotes wait for measurements despite fast drafting.|Removing another task may not improve overall performance.|Root Cause,Current State
Root Cause|The underlying mechanism explaining a problem, supported by evidence.|Duplicate orders arise from repeated requests without transaction identity.|Test the explanation against real normal and exception transactions.|Pain Point,Idempotency
Current State|How work actually operates today.|Invoices move through personal inboxes before approval.|Separate observed behavior from policy and desired improvements.|Future State,Process Mapping
Future State|The proposed way work will operate after changes.|Validated invoices enter a shared review queue.|Show ownership, exceptions and acceptance criteria.|Current State,Workflow
Process Mapping|Representing steps, decisions, systems and handoffs.|A map follows a request through approval and purchase release.|Use it to reveal missing inputs, waiting and unclear authority.|Workflow,Current State
ROI|Return on investment: comparing net benefit with investment cost over a stated period.|A pilot business case compares annual net capacity value with upfront cost.|State assumptions and distinguish modeled capacity from verified cash.|Payback Period,Operating Cost
Payback Period|The time modeled net benefit takes to cover the upfront investment.|A pilot with positive monthly benefit may recover cost after several months.|No positive net benefit means no modeled payback; timing and adoption matter.|ROI,Implementation Cost
Implementation Cost|The upfront effort and expense of designing, building, testing and handing over a change.|A proposal includes discovery, prototype, training and rollout effort.|Count delivery work, not just the software subscription.|Operating Cost,Scope
Operating Cost|Ongoing expense needed to keep the solution working.|Monitoring, software, API usage and repairs continue after release.|Subtract recurring costs when calculating net benefit.|ROI,Maintenance
Opportunity Cost|The value forgone by choosing one use of resources over another.|A complex agent project delays a simpler intake improvement.|Compare realistic alternatives and limited staff capacity.|Scope,ROI
Proof of Concept|A small experiment testing whether an approach can work at all.|Sample invoices are processed to test extraction feasibility.|It does not prove production reliability or adoption.|Prototype,Pilot
Prototype|An early working representation used to explore behavior.|A fictional intake form tests required fields and routing.|Use it to learn and expose gaps before commitments.|Proof of Concept,Production
Pilot|A bounded trial with representative users and explicit acceptance criteria.|Two buyers test intake and exceptions against a baseline.|Include real operating effort, adoption and a rollback decision.|Prototype,Success Metric
Production|The operational setting where real business work depends on the system.|An approved intake route handles actual customer requests.|Require ownership, monitoring, permissions and recovery.|Pilot,Production Environment
Scalability|The ability to handle greater workload while maintaining acceptable service and control.|A queue supports more requests without losing exceptions.|Check volume, review capacity and costs before expansion.|Rate Limit,Monitoring
Change Management|Helping people adopt a new process through involvement, communication and support.|Employees test exception handling and receive job aids.|A technically working tool can fail if it does not fit actual work.|Adoption,Training Plan
Adoption|People actually using the intended process correctly.|Buyers submit requests through the validated route instead of email.|Measure usage quality and workarounds, not just logins.|Change Management,KPI
KPI|A key performance indicator used to track an important outcome.|A service team measures urgent-request response time.|Choose measures that reveal business impact and harmful exceptions.|Success Metric,Bottleneck
Success Metric|A defined measurement used to decide whether a change worked.|Compare missing fields and re-entry minutes against a baseline.|Agree the target, source and measurement period before rollout.|KPI,Pilot
Scope|The agreed boundaries of work and deliverables.|The pilot covers intake, not autonomous purchasing.|State included work, exclusions and acceptance.|Scope Creep,Implementation Cost
Scope Creep|Uncontrolled expansion of work beyond agreed boundaries.|An intake pilot quietly adds billing and vendor negotiation.|Use documented impact estimates and approved changes.|Scope,Change Management
Baseline|The measured starting performance used for comparison.|Sample current invoice handling and exception effort before the pilot.|Compare similar work mixes so apparent savings are meaningful.|Success Metric,Pilot
Rework|Effort spent correcting or repeating previous work.|A revised layout requires recalculating an obsolete materials draft.|Prevent the cause before merely accelerating repeat effort.|Root Cause,Data Quality
Maintenance|Ongoing work to keep a solution reliable and fit for purpose.|An owner updates mappings and monitors failed requests.|Include it in scope, support ownership and recurring costs.|Operating Cost,Monitoring
Training Plan|A defined approach for helping employees operate the new process.|Staff practice routine requests, exceptions and recovery.|Verify practical ability rather than attendance alone.|Change Management,Adoption
`,
'Technical implementation':`
Frontend|The part of software people see and interact with.|This course's forms and dashboard are its frontend.|Design clear input, feedback and accessible workflows.|Backend,Data Validation
Backend|Software that performs service-side processing and manages protected operations.|A production connector validates permission before accessing accounting.|Secrets and privileged actions belong behind controlled service boundaries.|Frontend,API Key
Server|Software or a machine providing responses to other software.|The local course server serves browser files on this computer.|Understand where data is processed and who can reach the service.|Local,Hosting
Cloud|Computing services operated on remote infrastructure.|A hosted business database runs outside an employee's computer.|Review access, reliability, cost and data handling before use.|Local,Vendor Risk
Local|Running or storing information on the current device or local environment.|This course saves learner progress in this browser.|Local storage can be lost by clearing browser data and is not automatically encrypted.|Cloud,Environment
Hosting|Providing the environment where software is available.|A company hosts an internal workflow service.|Decide access, support and reliability needs before choosing a host.|Server,Deployment
Deployment|Making a version of software available in its intended environment.|An approved pilot configuration is released to selected employees.|Require tests, approval and recovery appropriate to that environment.|Environment,Production
Environment|The setting and configuration in which software runs.|A test workflow uses fictional records instead of live purchases.|Keep test and real business authority clearly separate.|Development Environment,Production Environment
Production Environment|The environment where actual business operations depend on the system.|The live order connector can commit real purchases.|Protect access, change control and recovery more carefully than a demo.|Production,Deployment
Development Environment|A setting for building and testing changes.|This local project develops the course without public deployment.|Use fictional data and controlled configuration before release.|Environment,Version Control
Version Control|Keeping a history of changes so versions can be reviewed or restored.|A developer records a tested workflow update.|It supports traceability, collaboration and safe repair.|Git,Repository
Git|A commonly used version-control system.|This course's upgrades are saved as local commits.|A local commit records changes; it does not deploy or publish them.|Version Control,Repository
Repository|The project files and their version history.|This course folder contains source and its Git history.|Keep credentials and unnecessary private records out of shared repositories.|Git,API Key
Dependency|An external component software relies on.|An application may rely on a library or a vendor connector.|Each dependency brings update, security and reliability responsibilities.|SDK,Vendor Risk
Latency|The delay before a system returns a result.|An assistant takes time to retrieve and summarize a document.|Measure whether the delay fits the workflow's service target.|Inference,Success Metric
Uptime|The proportion of time a service is available over a stated period.|A scheduling service reports its availability history.|Availability does not prove correct outputs or a suitable fallback.|Monitoring,Fallback
Logging|Recording events to help inspect what happened.|An integration records request IDs and error events.|Log enough for diagnosis without unnecessarily exposing sensitive data.|Audit Log,Observability
Monitoring|Checking operating health and raising actionable alerts.|An owner watches failed requests and exception backlog.|Specify who responds and what action is expected.|Logging,Escalation
Observability|The ability to understand internal operation from useful signals.|Request IDs, timings and errors explain why a job was duplicated.|Choose signals that support actual failure diagnosis, not just dashboards.|Logging,Monitoring
Upsert|An operation that updates an existing matching record or inserts one if none exists.|An integration uses the stable job ID to avoid creating another job on a retry.|Confirm the matching rule and database constraints; upsert alone does not guarantee every side effect is safe.|Idempotency,Stable Identifier
`,
'Workflow vocabulary':`
Purchase Order|A formal purchasing record specifying what the business intends to buy under its approved process.|An authorized buyer releases an order with reviewed quantities and delivery details.|Keep release authority separate from draft generation.|PO,Approval Gate
PO|The abbreviation for purchase order.|A supplier update refers to PO PS-204.|Use the exact order ID and approved revision when matching updates.|Purchase Order,Stable Identifier
Bill of Materials|The list of components and quantities required for a product or project.|A solar project needs an approved list of rails, clamps and modules.|The list should follow qualified specifications and controlled calculations.|BOM,Business Rule
BOM|The abbreviation for bill of materials: a specified list of components and quantities.|The reviewer checks the current BOM before purchase release.|A clear-looking AI draft is not a substitute for validated material rules.|Bill of Materials,Revision
Racking|The mounting structure and related components used to hold solar modules.|A layout specifies a compatible racking family for the installation.|A qualified reviewer must verify compatibility; this course does not provide engineering design rules.|Bill of Materials,Approval Gate
Reconciliation|Comparing records and resolving differences to establish an accurate agreed state.|A coordinator compares duplicate jobs against the original request.|Reconcile transaction state before resuming operations or repeating writes.|Record,Idempotency
Exception Queue|A visible list of work that needs clarification or special handling.|Requests missing project facts wait with a named owner and status.|Define ownership and response targets so held work does not disappear.|Exception,Escalation
Loaded Hourly Cost|An estimate of employee cost including pay and attributable overhead.|A business estimates hourly cost for modeling request-handling effort.|Document the assumption; dividing minutes by 60 is still necessary.|ROI,Capacity Value
Capacity Value|The modeled value of useful time released, without claiming an expense actually decreased.|A buyer can use saved handling hours on other supported work.|Apply realization and avoid presenting saved minutes as guaranteed cash or revenue.|ROI,Adoption
Warranty|The supplier or service terms governing covered repairs or obligations.|An HVAC coordinator asks an authorized person to resolve an unclear warranty request.|Do not let an assistant invent coverage or make unauthorized commitments.|Source of Truth,Approval Gate
Idempotent|Describes an operation designed so repeating the same request does not create another business effect.|A repeated job event still refers to the same controlled job.|Check every downstream effect, not only whether one table has duplicates.|Idempotency,Retry
`
};
export const reference=Object.entries(groups).flatMap(([category,text])=>text.trim().split('\n').filter(Boolean).map(line=>{const [term,definition,example,care,related]=line.split('|');return {term,id:term.toLowerCase().replace(/[^a-z0-9]+/g,'-'),category,definition,example,care,related:related.split(',')};}));
export const referenceCategories=Object.keys(groups);
const misconceptions={API:'An API is a communication interface, not AI and not permission to access every record.',RAG:'Retrieved passages can be irrelevant, outdated or misinterpreted; retrieval does not guarantee truth.',Hallucination:'Confident wording and correct formatting do not prove factual support.',Automation:'An automated process may use only fixed rules, with no AI at all.',Database:'Storage does not interpret language or independently make judgments.',Embedding:'Similar meaning does not establish identity, authority or correctness.',Token:'A token is not reliably one word; sizes differ by encoding and input.',Guardrail:'A prompt alone is not an enforceable permission boundary.',ChatGPT:'A chat conversation does not automatically connect to or control your company software.',Temperature:'A low setting is not a factual accuracy guarantee.'};
for(const entry of reference)entry.misunderstanding=misconceptions[entry.term]||'';
export const findReference=value=>reference.find(x=>x.id===value||x.term.toLowerCase()===String(value).toLowerCase());
