import {icon,methodComparison,visualLab} from './visual-learning.js';
import {findReference} from './reference.js';
import {lessonBridges} from './beginner.js';
const e=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

export function lessonHero(lesson,index,total){return `<header class="lesson-hero"><div class="hero-copy"><nav aria-label="Lesson breadcrumb"><a href="#course">Learning path</a><span aria-hidden="true">›</span><span>Level ${lesson.module}</span><span aria-hidden="true">›</span><span>Lesson ${index+1} of ${total}</span></nav><p class="eyebrow">${e(lesson.stage)} · ${lesson.time} MINUTES</p><h1>${e(lesson.title)}</h1><p>${e(lesson.why)}</p><a class="button light" href="#lesson-concept" data-local-anchor>Explore the concept ↓</a></div><div class="solar-art" aria-hidden="true"><div class="solar-sun"></div><div class="solar-panels"></div><div class="hero-principles"><span>${icon('decision')}Business goal first</span><span>${icon('rules')}Choose reliable methods</span><span>${icon('ai')}AI where it adds value</span><span>${icon('human')}Keep people accountable</span></div></div></header>`;}

export function lessonRail(lesson,summary,practice,mastered,draft=[],applied={}){const terms=lessonBridges[lesson.id]||[];return `<aside class="lesson-context"><section class="card lesson-itinerary"><p class="eyebrow">YOUR LESSON JOURNEY</p><h2>Understand. Then demonstrate.</h2><ol>${[['lesson-concept','Visual concept','Explore'],['lesson-example','Business example','Trace the boundaries'],['lesson-decisions','Make the decision',summary.assessed?'Submitted · '+summary.latest.score+'/100':draft.some(v=>v!==undefined&&v!=='')?'Draft · not assessed':'Not started · not assessed'],['lesson-assignment','Apply to a process',practice.assessed?'Submitted · '+practice.latest.score+'/100':Object.values(applied).some(v=>typeof v==='string'&&v.trim())?'Draft · not assessed':'Not started · not assessed']].map(([id,label,status],i)=>`<li><a href="#${id}" data-local-anchor><span class="itinerary-number">${i+1}</span><span><b>${label}</b><small>${e(status)}</small></span></a></li>`).join('')}</ol><p class="lesson-evidence-state">${icon(mastered?'success':'decision')}<b>${mastered?'Mastered':'Practical evidence required'}</b></p><small>Reading and guided examples do not award points.</small></section><section class="card lesson-glossary"><p class="eyebrow">CONTEXTUAL REFERENCE</p><h2>Key terms, within reach</h2>${terms.map(term=>{const entry=findReference(term);return entry?`<button class="glossary-preview" type="button" data-action="define" data-term="${e(entry.id)}"><span>${icon('system')}</span><span><b>${e(term)}</b><small>${e(entry.definition)}</small></span><span aria-hidden="true">›</span></button>`:'';}).join('')}<a href="#glossary">Explore the reference →</a></section><section class="card consultant-lens"><p class="eyebrow">CONSULTANT TAKEAWAY</p>${icon('human')}<p>${e(lesson.takeaway)}</p></section></aside>`;}

export function solarExample(){const steps=[
 ['system','Source package','Supplier email + controlled layout','“Please confirm delivery. A substitute may be available.”','Current revision · approved row count · approved design rule','Software preserves facts and versions. Missing fields block the calculation.'],
 ['ai','Interpret the note','Draft, with uncertainty visible','Delivery status: needs confirmation\nSubstitution: technical review required','Draft only · check against the original','AI interprets variable language. It does not invent dimensions, compatibility or quantities.'],
 ['rules','Calculate the quantity','Same approved input, same result','4 rows × 5 units per row\n= 20 training units','Approved training formula','Deterministic calculation uses approved inputs. This simplified training rule is not a real racking specification.'],
 ['human','Review the exception','A qualified person owns judgment','Check substitution compatibility\nResolve delivery uncertainty','Material reviewer','Human expertise resolves exceptions. A changed layout requires recalculation and fresh review.'],
 ['approval','Authorize the order','Authority before commitment','Reviewer approves the package\nAuthorized buyer releases once','Version-linked approval','An accurate calculation does not grant purchase authority. Software tracks the authorized order.']
];return `<section class="solar-example" id="lesson-example"><header><p class="eyebrow">WORKED BUSINESS EXAMPLE · FICTIONAL SOLAR PROCUREMENT</p><h2>Five boundaries. One reliable order.</h2><p>Follow the information from the source to release. Open a step to inspect its responsibility.</p></header><ol class="procurement-story">${steps.map(([type,label,title,sample,owner,why],i)=>`<li class="story-step type-${type}"><div class="story-top"><span class="node-index">${i+1}</span><span>${icon(type)}${label}</span></div><h3>${title}</h3><div class="story-specimen">${e(sample).replaceAll('\n','<br>')}</div><span class="story-owner">${e(owner)}</span><details><summary>Why this boundary matters</summary><div><p>${e(why)}</p></div></details>${i<steps.length-1?'<span class="story-arrow" aria-hidden="true">→</span>':''}</li>`).join('')}</ol><div class="mistake-comparison"><div>${icon('failure')}<h3>A confident draft can create a costly mistake.</h3><p>A model suggests <b>22 units</b>. The approved training formula gives <b>20</b>. Releasing the draft turns an interpretation error into an incorrect order.</p></div><div class="wrong-quantity"><span>AI DRAFT · UNVERIFIED</span><strong><s>22</s> → 20</strong><b>Use the approved rule</b></div></div></section>`;}

export function openingVisual(data={}){return `<section id="lesson-concept" class="lesson-concept-composition">${methodComparison()}</section>${solarExample()}${visualLab('solar',data.solar)}<div class="consultant-transfer">${icon('decision')}<div><b>Now make the consulting decision.</b><p>Separate interpretation, calculation, judgment and purchase authority. Your assessment tests those boundaries.</p></div><a href="#lesson-decisions" class="button" data-local-anchor>Make the decision →</a></div>`;}

export function activityBrief(page){const data={case:['DISCOVERY ENGAGEMENT','Question → evidence → hypothesis → recommendation',['Trace a transaction','Collect stakeholder evidence','Defend the recommendation'],'human'],map:['PROCESS STUDIO','Build the route. Assign the authority.',['Sequence the steps','Assign each owner','Protect the release gate'],'rules'],opportunity:['PRIORITIZATION STUDIO','Explore value against delivery constraints.',['Rate evidenced factors','Inspect the tradeoff','Choose a bounded pilot'],'decision'],roi:['FINANCIAL WORKBENCH','Change an assumption. Inspect the business effect.',['Measure active effort','Include review and support','Challenge the downside'],'system'],failure:['INCIDENT RESPONSE','Contain the harm before repairing the mechanism.',['Contain duplicate dispatch','Diagnose the retry','Verify recovery'],'failure'],capstone:['INDEPENDENT ENGAGEMENT','Produce an evidence-backed consulting package.',['Gather evidence','Develop deliverables','Defend the design'],'approval']};if(!data[page])return '';const [label,title,steps,type]=data[page];return `<section class="activity-brief type-${type}"><div>${icon(type)}<span class="eyebrow">${label}</span><h2>${title}</h2></div><ol>${steps.map((s,i)=>`<li><span>${i+1}</span>${s}</li>`).join('')}</ol></section>`;}
