export const ASSESSMENT_REVISION = '1.1';
// Each option teaches a decision boundary, including when it would be appropriate.
export const choice = (text, rationale, consequence, when) => ({text,rationale,consequence,when});
export function decision(id,prompt,evidence,lens,choices,correct) {
  return {id,prompt,evidence,lens,choices,options:choices.map(c=>c.text),correct,why:choices[correct].rationale};
}
const c=choice, q=decision;
export const lessonAssessments = {
fit:[
q('fit-intake','Of 80 purchase requests, 28 lack a delivery date. Entry takes three minutes; clarification takes a day. What is the best first change?','Missing dates cause the longest delay; there is no evidence that extracting existing text is the constraint.','Improve the input contract before improving the speed of processing.',[
c('Extract delivery dates from request emails, then have buyers verify the proposed dates.','Useful extraction cannot recover a date the requester never supplied.','Buyers still chase missing dates while supporting an extra component.','Use extraction if dates are consistently present in varied documents.'),
c('Require delivery date at intake, route urgent exceptions to a buyer, then measure clarification.','This removes the documented source of waiting without assuming all requests fit one path.','Complete requests progress sooner; urgent exceptions retain an accountable route.','This remains preferred while incomplete inputs dominate delay.'),
c('Create a shared request queue with a daily buyer review and overdue-request alerts.','Visibility helps coordination but does not ensure a required date exists.','The queue exposes the backlog without necessarily reducing clarification.','Prioritize a queue when complete requests wait because ownership is unclear.')],1),
q('fit-language','A team handles 300 vendor emails monthly. Descriptions vary, but PO totals follow approved rules. Which pilot best fits AI?','Free-text categorization is variable; approved totals have a deterministic specification.','Choose technology separately for interpretation, calculation and authorization.',[
c('Have a model calculate a draft total and compare it with the existing spreadsheet.','A comparison experiment is possible, but adds little value to a working rule calculation.','The team maintains two calculation paths without addressing email sorting.','A model may explain calculation results; the approved rules should still compute them.'),
c('Create fixed sender-and-keyword routing rules, and review every unmatched message.','This is a sound baseline but may miss varied descriptions if sender and keywords are weak predictors.','Many messages may remain unclassified despite reliable rule execution.','Prefer rules when a small stable set of senders or terms explains the categories.'),
c('Use AI to propose email categories for review, while keeping PO totals in approved formulas.','It targets varied language and preserves repeatable calculations.','Reviewers can measure category errors without exposing purchasing authority.','Keep this pilot only if it improves on the rule baseline after review time.')],2),
q('fit-existing','A booking tool already sends reliable reminders. Missed appointments are 3%; no baseline links them to reminder content. What should you do?','The outcome problem has not been attributed to reminders; reliability alone does not prove reminder wording is the cause.','A working system deserves evidence before replacement.',[
c('Keep the tool and sample missed appointments to distinguish delivery, timing and customer constraints.','This tests the business cause before committing effort to an unproven change.','The owner gets a targeted next action rather than a new subscription.','Replace the tool if evidence shows it cannot meet delivery or scheduling requirements.'),
c('Pilot personalized AI reminder wording for one month using the current sending tool.','A low-risk experiment is possible, but its hypothesis lacks evidence here.','You may attribute unrelated seasonal changes to wording.','Use this experiment when messages are delivered and customers report unclear instructions.'),
c('Move reminders into the CRM so booking and customer records share one workflow.','Consolidation can reduce handoffs, but this case has not shown fragmented records.','Migration and staff retraining may exceed the benefit from a 3% issue.','Consider consolidation when mismatched customer data demonstrably causes missed reminders.')],0),
q('fit-missing','An owner says “Our staff spend too long answering emails; I want an agent.” Which evidence package is needed before recommending one?','No volume, categories, existing response process or error consequences have been established.','Discovery should distinguish repetitive answers from judgment-heavy conversations.',[
c('Measure total response time, staff hourly cost and the budget available for a pilot.','This estimates cost but cannot establish which replies may safely be automated.','A promising ROI may conceal sensitive or difficult cases.','Use these measurements after classifying the work and risk boundaries.'),
c('Review existing templates, CRM integrations and which assistant the employees already use.','Tool fit and adoption matter but do not characterize demand or escalation.','A convenient integration may solve only a small portion of the work.','Use this package once request types, volume and decision consequences are known.'),
c('Sample volume, request types, templates, customer data, escalation, response targets and error consequences.','This reveals both the addressable routine work and the boundaries requiring judgment.','The recommendation can be a template change, rules or AI based on actual work.','A simpler template audit may suffice if nearly all requests are already standardized.')],2)
],
reliability:[
q('reliability-facts','An invoice extractor returns valid JSON for 99% of 200 samples, but seven bank details disagree with the source. What should the pilot prioritize?','Schema success is high while factual disagreement affects payment routing.','Format validity and factual accuracy are different acceptance tests.',[
c('Compare a stronger model on the same samples and select the model with the lowest field-error rate.','Model selection is useful, but even a better model requires independent payment controls.','A lower average error rate may still permit a wrong bank change.','Use comparison after establishing source checks and controlled downstream actions.'),
c('Check critical fields against originals and approved vendors, with separate bank-change verification.','It protects the business effect independently of model confidence and formatting.','Uncertain records wait for review instead of becoming payment instructions.','Reduce review only for proven low-risk fields under an approved policy.'),
c('Require confidence values per field and route values below a threshold to reviewers.','Confidence is a useful signal only after calibration against representative failures.','Confident but incorrect bank details could avoid review.','Use calibrated thresholds for bounded low-risk extraction, not bank authority.')],1),
q('reliability-injection','A supplier PDF includes instructions to export customer records. The assistant only needs shipment status. Which control matters most?','Document text is untrusted and customer export is outside the task.','Enforce permission boundaries outside the model.',[
c('Give the assistant read-only shipment access and enforce allowed tools and arguments outside document text.','The unauthorized action cannot execute even if the model follows the document instruction.','The attempted instruction is contained and can be logged for review.','Broader tools require a separate need, approval and tested control boundary.'),
c('Strip instruction-like sentences before passing PDFs to the shipment assistant.','Filtering reduces exposure but cannot reliably recognize every adversarial phrasing.','A missed instruction could still reach any broadly granted tools.','Use filtering as a supplementary control, never the sole permission boundary.'),
c('Use a second model to review proposed tool calls before the assistant executes them.','A second model may catch some errors but is also probabilistic and adds latency.','Both models may accept the same unsupported request.','Use model review to assist a deterministic allowlist and human gates.')],0),
q('reliability-pilot','A team has 40 clean invoice samples and 12 months of mixed PDFs and photos. What is the strongest first pilot design?','The sample currently excludes the difficult formats and exceptions likely to dominate production review.','Test the distribution of work, not only the most convenient examples.',[
c('Start with the clean samples, prove the integration, then enable the same flow for all invoices.','This proves plumbing but not realistic reliability.','The first broad rollout could create an unexpected exception backlog.','Use clean samples only for an early technical smoke test.'),
c('Sample random invoices across the year and report average extraction accuracy before rollout.','Representative sampling helps, but an average can hide high-impact errors and approval gaps.','A good headline accuracy can obscure unacceptable payment-field mistakes.','Use this metric alongside field-level severity, review time and approval tests.'),
c('Use approved redacted samples across formats and exceptions; measure critical-field errors and review effort.','It evaluates real operational reliability and protects sensitive data during the pilot.','The team can reject a fast extractor that creates too much review or risk.','Add controlled production data only after permissions and processing terms are approved.')],2),
q('reliability-failure','A supplier-status agent has read-only tools. Two sources disagree on a delivery date. What should the next step be?','Both sources are permitted, but neither is confirmed authoritative for the conflicting update.','Safe permissions do not remove uncertainty in the evidence.',[
c('Use the newest message as the delivery date and include a link to that source.','Recency alone cannot distinguish an informal estimate from an approved commitment.','The coordinator may plan an installation on an unconfirmed date.','Use the newest source only when a documented authority rule makes it controlling.'),
c('Return both dated sources, flag the conflict, stop retries and ask the coordinator to verify.','It makes uncertainty actionable instead of choosing a convenient answer.','A person verifies the commitment before downstream scheduling.','Automate selection later if the business defines a reliable source-priority rule.'),
c('Query both sources again and continue until their dates agree.','More calls can help transient failures but may never resolve a genuine contradiction.','An unbounded loop adds cost and hides a decision that needs an owner.','Use bounded retries when the inconsistency is known to result from delayed synchronization.')],1)
],
discovery:[
q('discovery-trace','An HVAC owner wants faster quoting. Staff say quotes take two days; typing a quote takes eight minutes. What should you ask first?','Elapsed delay greatly exceeds active drafting time; the cause is not established.','Trace one transaction before accepting the owner’s proposed solution.',[
c('Which quote templates and customer categories could support a drafting assistant?','This characterizes drafting but assumes drafting is the bottleneck.','You may save minutes while quotes still wait two days.','Ask this after evidence shows drafting quality or active writing is the constraint.'),
c('How many quotes are produced monthly and what is the cost per quote?','Frequency and cost establish scale but do not locate the waiting.','A high-volume estimate could justify the wrong intervention.','Use volume and cost to value a bottleneck identified through transaction tracing.'),
c('Can we follow a recent quote from request through measurements, approval and customer delivery?','A transaction trace separates missing inputs, queues and drafting time.','The recommendation can target the stage actually delaying the customer.','A template audit is sufficient only when the trace already confirms a drafting constraint.')],2),
q('discovery-estimate','An employee says invoice entry takes 15 minutes. Thirty percent are exceptions; clean invoices look faster. Which baseline is defensible?','A single estimate mixes different work types and may overstate the addressable routine labor.','Measure the work mix and the cost of exceptions.',[
c('Use 15 minutes as a conservative baseline and apply a 50% savings factor.','A discount does not correct a biased or unclear sample.','The business case may still price the wrong process frequency or review burden.','Use a labeled estimate for early screening, with explicit uncertainty and no commitment.'),
c('Time a sample of clean and exception invoices, recording their frequencies and review effort separately.','It supports a weighted baseline and a realistic future review cost.','The owner sees which portion of work the pilot can actually improve.','A larger sample becomes necessary if types or seasonal volumes vary materially.'),
c('Use accounting-system timestamps for all invoices to calculate an objective average duration.','Timestamps measure elapsed time, which may include waiting rather than labor.','The calculator may value two days of waiting as paid processing time.','Use timestamps for queue delays; combine them with observation for active labor.')],1),
q('discovery-tacit','One purchasing employee handles most unusual supplier requests. Which question best uncovers continuity risk?','Standard procedure does not describe how unusual requests are resolved.','Find the judgments and evidence that live only in a person’s memory.',[
c('Show an unusual order you resolved, the clues you used and who could handle it during your absence.','A real exception reveals rules, judgment and recovery ownership.','The team can document decision boundaries without pretending every exception is routine.','Use a general skills inventory after tracing representative exception decisions.'),
c('Which supplier contacts and document folders should be shared with another buyer?','Shared access helps but does not explain how the employee makes decisions.','A replacement may have the documents yet still choose an incompatible substitution.','Prioritize access when the decisions are already documented and only information is unavailable.'),
c('Can we turn your standard procedure into a searchable FAQ for new buyers?','A knowledge base helps repeatable questions but can omit undocumented exceptions.','The assistant may give incomplete guidance confidently.','Build the FAQ once exception paths and approval requirements have been validated.')],0),
q('discovery-next','The email-intake owner reports 600 messages monthly. You know volume and cost but not content. What is still missing before a solution recommendation?','The complaint and volume establish a possible opportunity, not a safe automation boundary.','The next discovery question should reduce a decision-relevant uncertainty.',[
c('Preferred software platform, implementation budget and the month they want to launch.','Constraints matter but do not show which messages need human judgment.','A feasible implementation may automate the wrong class of responses.','Ask these once the process and data boundaries are understood.'),
c('Average message length, common attachment formats and the staff’s current prompt-writing experience.','These describe implementation inputs without identifying business consequences.','A technically capable pilot can miss escalation or sensitive content.','Use them to estimate effort after classifying requests and responsibilities.'),
c('Request types, existing templates, sensitive data, escalation owners and consequences of a wrong response.','These facts establish addressable work and the actions that should remain controlled.','You can compare a template improvement, routing rules and reviewed AI drafting.','If these are already documented, validate them with an employee transaction sample.')],2)
],
diagnosis:[
q('diagnosis-wait','Purchase requests take four days. Entry takes five minutes; approvals are reviewed only on Fridays. What is the best first hypothesis?','The weekly decision queue creates a plausible delay mechanism larger than entry effort.','Locate the constraint before optimizing a visible task.',[
c('Manual entry creates a queue that could be reduced with document extraction.','This may reduce labor, but the reported approval schedule remains a larger constraint.','Requests entered faster can still wait for Friday.','Choose extraction if measured entry backlog exceeds approval waiting.'),
c('Approval cadence and decision ownership dominate lead time; validate request and approval timestamps.','It targets the mechanism supported by the evidence while treating it as a testable hypothesis.','A policy or delegated approval may reduce days without adding a model.','Automation becomes useful after a clear approval rule and authority boundary exist.'),
c('Employees need status visibility so they can follow up on overdue requests.','Visibility may help exceptions but does not change the normal Friday cadence.','Staff may spend more time chasing an unchanged policy.','Use alerts when approvals are available daily but requests are overlooked.')],1),
q('diagnosis-identity','Dispatch and billing record the same customer differently. Both teams’ entry is individually accurate. What should precede a connection?','The error appears at the cross-system identity boundary, not necessarily inside either team’s entry task.','Integration depends on shared identity and data ownership.',[
c('Use fuzzy customer-name matching and ask staff to review low-confidence matches.','Matching can help migration but may conceal different customers with similar names.','Some joins could silently connect the wrong service history and invoice.','Use reviewed matching to clean legacy records after defining canonical IDs.'),
c('Choose one CRM to replace both systems and eliminate the separate records.','Consolidation may be sound but carries migration and adoption effort not yet justified.','A broad system replacement delays a smaller identity correction.','Replace systems if current products cannot support shared IDs or required ownership.'),
c('Agree on a canonical customer/job ID, ownership and matching rules, then validate integration on samples.','It addresses the interface contract while preserving working systems where possible.','Retries and updates can refer to the same transaction reliably.','A migration is appropriate if shared identity cannot be implemented reliably in current tools.')],2),
q('diagnosis-evidence','Twelve of 20 delayed jobs lacked approved measurements. Five complete jobs also waited on approval. What is a defensible diagnosis?','Two observed mechanisms exist; missing measurements are frequent but do not explain all delays.','A useful root-cause statement acknowledges contrary evidence.',[
c('Missing measurements are a leading hypothesis; separate those waits from approval waits in a larger sample.','It uses the strongest signal without claiming that all delays share one cause.','The pilot can address intake and track whether a second constraint emerges.','A narrower claim is appropriate once repeated evidence establishes a dominant mechanism.'),
c('Require measurements at intake; the sample proves this is the sole root cause.','The proposed change is reasonable but the causal claim ignores five complete jobs.','The owner may expect all delays to disappear and lose trust in the pilot.','Use a single-cause claim only after explaining or ruling out the contrary cases.'),
c('Redesign both intake and all approval rules at once to cover every observed delay.','It covers both mechanisms but expands scope before their relative impact is known.','The team may not know which change created the benefit or the disruption.','A combined change is justified when dependencies or urgent harm make separate pilots impractical.')],0),
q('diagnosis-disprove','You suspect missing measurements delay quotes. Which finding would most weaken that hypothesis?','A diagnosis must predict differences between otherwise comparable transactions.','Ask what evidence would prove your recommendation wrong.',[
c('Employees say the intake form is frustrating and customers prefer calling.','This reveals adoption risk but does not show whether missing measurements drive delay.','You could confuse usability feedback with causal evidence.','Use interviews to explain how the measured missing-data mechanism occurs.'),
c('Complete and incomplete requests have similar elapsed times because both wait on the same approval queue.','The comparison suggests another shared constraint dominates the measured delay.','An intake-only pilot may improve quality without delivering the promised speed.','Intake remains valuable if its separate error or rework benefit is supported.'),
c('The same volume of requests arrives each month despite the proposed intake improvement.','Stable volume does not test the relationship between completeness and delay.','You may reject an improvement using an unrelated outcome measure.','Use volume when the objective is throughput and demand limits the benefit.')],1)
],
current:[
q('current-boundary','A service request sometimes reaches dispatch with no address. What should the current-state map show?','Dispatch may receive an event before it receives enough information to act.','Separate the arrival trigger from the validity check.',[
c('Record request arrival, required fields and the actual return-to-coordinator path for incomplete requests.','It exposes the real trigger, data contract and rework handoff.','Employees can validate the map and identify avoidable clarification.','A simplified happy-path diagram is useful after exception paths have been documented elsewhere.'),
c('Start the map when dispatch has a complete request, then document downstream work in detail.','This makes dispatch clear but omits the upstream waiting under investigation.','The map may show a fast process while hiding the real customer delay.','Use this boundary if scope explicitly begins at accepted, complete requests.'),
c('Start at customer contact and group intake, validation and assignment into one office step.','This is concise but hides the ownership and return path causing rework.','The consultant may assign one duration to several different queues.','Group steps in an executive summary after retaining the detailed operational map.')],0),
q('current-exception','Staff usually call customers for missing details; some requests remain in personal inboxes. How should this appear in an as-is map?','The exception behavior is inconsistent and not fully visible in a shared queue.','Document reality before prescribing the cleaner future state.',[
c('Draw a centralized exception queue and assign the coordinator as its owner.','That is a reasonable future-state design, not evidence of current behavior.','The owner may think the missing-request risk is already controlled.','Use this design in a separately labeled proposed workflow.'),
c('Show the actual callback and personal-inbox branches, including unclear ownership and waiting.','It accurately exposes the inconsistency and supports redesign discussion.','The team can identify lost requests and agree on a future owner.','Collapse branches later if observation shows equivalent behavior and responsibility.'),
c('Mark incomplete requests as an exception note below the main sequence.','A note acknowledges the issue but hides its handoffs and unresolved queues.','The consultant may undercount time and miss where requests disappear.','Use a note for truly rare exceptions that do not materially affect the objective.')],1),
q('current-queue','A map shows “manager approves.” Review takes two minutes; requests wait 36 hours. What information adds the most diagnostic value?','Waiting, rather than the action itself, dominates the step’s elapsed time.','Map decision availability and ownership as well as work effort.',[
c('Record approval thresholds and show which automation platform could apply them.','Rules are useful design inputs, but the current delay may be availability rather than complexity.','You may automate the decision logic while retaining the same release queue.','Prioritize rule detail if inconsistent decisions, not waiting, drive the complaint.'),
c('Record the manager’s review duration and the number of requests per month.','This estimates labor without explaining the 36-hour queue.','The ROI can overfocus on two minutes and miss the lead-time constraint.','Use these figures when calculating active cost after the queue mechanism is known.'),
c('Record when requests enter the queue, who can approve, review windows and escalation routes.','It identifies the availability and authority mechanism causing the wait.','A delegated gate or changed review cadence becomes a defensible option.','Add technical automation only if the business approves a repeatable authority rule.')],2),
q('current-missing','A lead-to-sale map names every step but no owner for pricing exceptions. What must be verified before using it to design automation?','The normal sequence is complete, but exceptional pricing is not assigned to an accountable decision-maker.','An unowned exception is a missing part of the process.',[
c('Who decides an unusual discount, what evidence they need and where the lead waits until approval.','It establishes decision authority, inputs and the exception path before tools are assigned.','Automation can route exceptions instead of making undocumented commitments.','A routine price rule can replace the gate if an authorized policy explicitly allows it.'),
c('Which CRM has the best discount workflow and can store the lead history.','Product capability does not establish the business’s discount authority.','The tool may encode a policy nobody has agreed to.','Compare products once decision ownership and requirements are documented.'),
c('How frequently discounts occur and the average dollar value of each discount.','Value and frequency help prioritize but do not determine who may authorize one.','A high-volume exception remains an uncontrolled decision.','Use these figures to justify redesign once ownership is clear.')],0)
],
future:[
q('future-substitution','A solar supplier proposes a cheaper racking substitute. The approved BOM specifies another family. What is the best next action?','A price advantage does not establish technical compatibility with the approved layout and BOM.','Separate commercial value from technical authority.',[
c('Compare the supplier data sheets and ask the buyer to sign off the cost benefit.','The buyer may assess commercial terms but not have qualified compatibility authority.','A cheaper purchase can create an installation incompatibility.','Use buyer signoff for price-only changes already covered by approved compatibility rules.'),
c('Keep the original component and request a quote from a different supplier.','This preserves the design but may unnecessarily ignore a safe alternative.','The project could miss a delivery window without assessing the actual substitution.','Keep the original when no qualified review is available or compatibility cannot be established.'),
c('Route the substitute and design revision to a qualified reviewer before changing quantities or releasing an order.','It preserves engineering accountability while allowing a potentially useful alternative.','The business can approve savings without losing control of the approved specification.','A deterministic preapproved substitute list can handle routine equivalents later.')],2),
q('future-retry','A connection times out after an order request may already have reached the distributor. What must the workflow do?','The system does not know whether the business effect happened; this is not just a missing response.','Retry the transaction safely, not merely the network call.',[
c('Reconcile by a stable order ID, retry idempotently within limits and notify an owner if status stays uncertain.','It prevents a second order while making unresolved status visible.','The buyer can complete recovery without duplicate purchasing.','A simple retry suffices only when the receiving operation is confirmed idempotent.'),
c('Retry three times with longer delays, then ask the buyer to place the order manually.','Bounded retries are useful, but the manual route can duplicate an already accepted order.','A delayed response may become two purchases.','Use this recovery once the buyer checks whether the first order exists.'),
c('Send an automatic cancellation before resubmitting the order through a second connection.','Cancellation has its own uncertain status and may undo a valid purchase.','The process adds more side effects to an unresolved transaction.','Use cancellation only after confirmed state and an authorized business decision.')],0),
q('future-first','Three buyers use different quantity Sheets. New software can connect all of them. What should precede the connection?','The inconsistency lives in rules and versions, so integration alone can spread conflicting results.','Standardize the decision contract before scaling its execution.',[
c('Consolidate the Sheets into a database and retain each buyer’s formulas as separate views.','Central storage improves visibility but preserves inconsistent business logic.','The same project can still produce different approved-looking quantities.','Retain separate views when legitimate project-specific rules are explicitly governed.'),
c('Agree on approved formula ownership, revision fields and validation, then implement one calculation path.','It removes the inconsistency before improving data movement.','Buyers work from the same controlled rule and current project revision.','A broader tool migration is justified if the current platform cannot protect these contracts.'),
c('Add an AI comparison step that flags differences between the three Sheets for review.','Comparison helps detect discrepancies but leaves every transaction dependent on reconciliation.','Review burden and ambiguity may remain high despite better alerts.','Use comparison temporarily during migration to a single approved rule set.')],1),
q('future-revision','Revision B arrives after revision A was approved but before its PO was released. What should the workflow invalidate?','The approval is linked to inputs that have changed; no purchase has yet been committed.','Approval is evidence about a version, not a permanent property of a project.',[
c('Update the project record and retain approval if the total module count is unchanged.','Equal module count does not prove racking layout and material quantities are unchanged.','An old approval can authorize the wrong arrangement.','Retain approval only for changes explicitly proven immaterial under an approved policy.'),
c('Release revision A’s PO and manage differences later through a change order.','This may preserve a schedule but commits avoidable rework before assessing the revision.','The team may purchase excess or incompatible material.','Use a controlled change order when the original order is already binding and an owner approves recovery.'),
c('Hold release, recalculate affected quantities and obtain revision-linked material approval again.','It restores the relationship between the approved evidence and the order.','The released PO refers to the current, reviewed design.','Automate the impact check only under validated rules and an explicit reapproval policy.')],2)
],
value:[
q('value-feasibility','A workflow promises $2,000 monthly capacity value, but 35% of records lack required data and 25% need judgment. What is the best first pilot?','The gross value does not account for data cleanup or exception review.','Treat feasibility and risk as constraints on realizing benefit.',[
c('Automate the complete-record subset and estimate savings from its volume alone.','This is bounded, but only if the subset is representative and does not move the bottleneck elsewhere.','An isolated demo may underestimate review and upstream cleanup effort.','Use a subset pilot after verifying its boundaries and counting excluded work.'),
c('Measure and repair required-input gaps, then pilot the stable subset with explicit exception ownership.','It improves the causes limiting realized value while keeping judgment controlled.','The business can measure net benefit rather than gross processing speed.','A larger pilot becomes appropriate when missing inputs and exception rates are reliably controlled.'),
c('Prototype an AI assistant for missing-field inference and keep every inferred record under review.','Reviewed inference can help, but missing authoritative facts may not be inferable.','Reviewers may spend more time rejecting plausible guesses than collecting the correct data.','Use extraction or inference when approved source evidence actually contains the missing facts.')],1),
q('value-complexity','A form, Sheet and notification meet the agreed intake requirements. An agent approach costs $4,000 more and saves no measured extra time. What is the defensible choice?','The more flexible design has a known additional cost and no demonstrated additional business benefit.','Price flexibility only when the business needs it.',[
c('Choose the agent design because future exceptions may justify flexibility.','Future option value is possible but remains an unmeasured assumption here.','The client pays for capability without an agreed use case or support plan.','Choose added flexibility if likely, valuable exceptions cannot be handled by stable rules.'),
c('Build both approaches in parallel and compare them after a month.','A comparison can teach, but duplicates effort for a requirement already met by the simpler option.','The pilot’s cost rises before the team has identified a meaningful difference to test.','Run both when uncertainty about material performance cannot be resolved by a smaller experiment.'),
c('Use the form-based pilot and list specific future conditions that would justify an agent later.','It meets the current goal while retaining a testable path for expansion.','The owner gets lower support cost and clearer criteria for future investment.','Revisit agents if variable planning becomes a verified bottleneck with controlled actions.')],2),
q('value-capacity','A pilot frees 20 hours monthly but staffing, revenue and overtime are unchanged. Which benefit claim is strongest?','Time has been released, but no change in cash expense or measured output has been shown.','Keep measured operational benefit separate from financial realization.',[
c('Report released capacity and observe whether it reduces overtime or increases valuable output before claiming cash benefit.','It states what the evidence proves and identifies how value could later be realized.','The owner avoids budgeting a payroll reduction that has not occurred.','Claim cash savings once an actual expenditure change is verified.'),
c('Value all 20 hours at the loaded wage and label the result a monthly cost reduction.','The wage values capacity but does not prove expenditure fell.','The business case may overpromise money available for investment.','Use this value as modeled capacity with an adoption/realization assumption.'),
c('Value the 20 hours at expected sales per hour and call the result additional revenue.','It assumes demand and conversion that the pilot did not measure.','The owner may double-count capacity and speculative sales.','Estimate revenue separately when demand, throughput and contribution margin are evidenced.')],0),
q('value-downside','A pilot has positive payback at 90 monthly requests and 75% realized capacity. What would most challenge the investment?','The result depends on assumptions about demand, adoption and review effort.','Test the assumptions most capable of reversing the decision.',[
c('Compare the annualized gross labor saving with implementation cost at the current assumptions.','This restates the favorable case and may omit recurring costs.','The decision remains fragile if adoption or volume falls.','Use gross figures only as an initial ceiling before a net-benefit calculation.'),
c('Model lower volume, 50% realization and higher review/support cost; check whether net benefit stays positive.','It tests plausible conditions that can remove payback.','The owner can choose a smaller pilot or defer a fragile investment.','A narrower sensitivity range is justified after actual adoption and support costs are measured.'),
c('Compare the current software price with two other vendors offering similar features.','Price comparison may help but ignores larger process and adoption assumptions.','A cheaper subscription can still have poor realized ROI.','Prioritize vendor comparison when recurring software price dominates total cost.')],1)
],
delivery:[
q('delivery-adoption','After training, a coordinator still uses email because the new form cannot record urgent callbacks. What is the best response?','The workaround addresses an unmet workflow requirement, not merely a lack of training.','Adoption problems can be evidence about the design.',[
c('Run another training session and ask the manager to reinforce the new process.','Training helps knowledge gaps, but the stated callback requirement remains unsupported.','Staff may hide workarounds rather than reliably capture urgent jobs.','Use reinforcement after the workflow accommodates legitimate work and staff can perform it.'),
c('Require all requests through the form and add an urgent-priority flag.','A priority flag may help, but it may not capture callback ownership or timing.','The form can receive urgent items without ensuring someone acts on them.','Use this change once observation confirms the missing field is the only gap.'),
c('Observe urgent callbacks, add a bounded owned path and test it with the coordinator before reinforcing adoption.','It addresses the functional gap and involves the person doing the work.','The new route can replace the workaround without losing urgent service.','Training alone is appropriate when the route already supports the task reliably.')],2),
q('delivery-duplicate','Logs show the same webhook event created three records after timeouts. What is the strongest prevention?','Retries represent one business transaction, not three independent requests.','Reliable automation must tolerate repeated delivery.',[
c('Use a stable event/job key and idempotent update, then test replay, bounded retries and reconciliation alerts.','It removes duplicate business effects and makes unresolved failures owned.','A repeated event updates or skips an existing job rather than creating another.','Batch reconciliation can supplement this when legacy systems cannot support atomic updates.'),
c('Increase the timeout and reduce retry frequency to avoid overlapping requests.','This reduces the chance of duplication but does not prevent a repeated event from creating a new record.','A slower connection or replay can reproduce the same defect.','Tune timeout values after idempotency is established.'),
c('Create a nightly duplicate-detection job and have staff merge matching records.','Detection is useful but the duplicate may already trigger dispatch or billing.','Staff inherit cleanup work and the business can act on incorrect records first.','Use reconciliation as a containment measure while the write path is repaired.')],0),
q('delivery-scope','The owner asks for five extra workflows during a two-week pilot. One uses the same form fields but different approval rules. What is the best response?','Shared fields do not imply shared risk, testing or authority boundaries.','Scope is defined by business behavior as well as technical components.',[
c('Add the similar workflow now and defer the other four to maintain momentum.','Similarity may reduce build effort but does not establish approval or acceptance requirements.','The pilot can expand into an untested authority boundary.','Include it only after confirming dependencies, risk and revised acceptance with the owner.'),
c('Estimate impact, document exclusions/dependencies and ask the owner to approve a separate change or later phase.','It protects the original experiment and makes the tradeoff visible.','The client chooses scope using a realistic cost and delivery implication.','A small change may fit the pilot if impact is negligible and explicitly approved.'),
c('Replace one original deliverable with the extra workflow so the total number of workflows stays constant.','Equal counts do not imply equal effort or business value.','The agreed outcome may be lost despite an apparently unchanged project size.','Trade scope when effort, risk and the business outcome are re-estimated and accepted.')],1),
q('delivery-proof','Intake processing is faster in a pilot, but several urgent requests still wait overnight. Which acceptance approach is strongest?','Average speed can hide a harmful exception affecting the business service promise.','Acceptance must reflect the outcome distribution and risk, not only an average.',[
c('Compare baseline/pilot active time, missing fields, urgent escalation time and adoption; review unresolved exceptions.','It tests both the intended efficiency gain and the service boundary the pilot must protect.','The owner can accept, refine or stop the rollout based on actual business effects.','A narrower metric set is appropriate for a low-risk process with no material exception path.'),
c('Extend the pilot until average processing time consistently reaches its target.','Consistency is useful but average processing can improve while urgent service remains poor.','The team may accept a workflow that misses its most important cases.','Use an average after adding separate measures for high-impact exceptions.'),
c('Count complete form submissions and compare user satisfaction with the old intake method.','Adoption and sentiment matter but do not prove response time or correct handling.','A popular form can still leave urgent work unowned.','Use these as supporting measures alongside outcome and exception evidence.')],0)
]
};

export const practiceFields=[
  ['process','Process',12],['goal','Business goal',20],['pain','Current pain and evidence',30],['root','Root-cause hypothesis and validation',30],['improvement','Proposed improvement',30],['deterministic','Deterministic steps and why',25],['ai','AI-assisted steps (or explain why none)',25],['human','Human approval and exception owner',25],['metric','Success metric and baseline',25]
].map(([id,label,min])=>({id,label,min}));
// Different applied problems provide evidence beyond recognizing a lesson answer.
export const practiceAssessments={
fit:[q('practice-fit-tools','A wholesaler has approved reorder thresholds. Staff spend 30 hours monthly reading 600 varied delay emails; keyword rules miss urgent changes. Which small pilot best assigns the two steps?','Thresholds are approved; varied language creates measured review effort and missed urgency. Compare net benefit before expanding the pilot.','Use one architecture with different methods for different steps.',[
c('Use rules for reorder suggestions and reviewed AI summaries for unusual delay messages.','The methods match each step’s uncertainty.','Calculations remain stable and message interpretation remains reviewable.','Extend AI only if another unstructured task produces measurable value.'),c('Use one reviewed model for both tasks so staff learn one interface.','One interface is convenient but does not justify replacing approved arithmetic.','Reviewers must validate avoidable quantity uncertainty.','A shared interface can call deterministic tools instead of asking the model to calculate.'),c('Use rules for both tasks and ask staff to manually summarize unmatched delay emails.','This is a reasonable baseline but may leave the language bottleneck unresolved.','Manual review effort may remain high.','Prefer this when the unmatched email volume is too low to justify AI.')],0),
q('practice-fit-check','Before adding AI summaries, what would you compare?','The goal is useful coordinator capacity, not simply produced summaries.','Evaluate review effort and error consequences against a non-AI baseline.',[
c('Subscription price and total monthly token volume.','These estimate one cost but omit staff effort and output usefulness.','A cheap service may require costly correction.','Use these after measuring reviewed output performance.'),c('Net staff time, material omissions and usable follow-ups versus templates or manual handling.','It tests the business value after review.','The buyer can reject a fluent but unhelpful summary tool.','Use a narrower comparison if the task has only one approved output requirement.'),c('User preference for the summary’s tone and readability.','Readability matters but does not establish accuracy or saved effort.','Staff may prefer a summary that hides a missed delivery commitment.','Measure tone after factual usability is established.')],1)],
reliability:[q('practice-reliability-boundary','An onboarding assistant drafts answers using approved policies. Which permission design fits a first pilot?','It needs policy retrieval but not authority to change employee records.','Role and tool permissions should follow the objective.',[
c('Read policies and update HR records only after a second model verifies each change.','Model review does not establish HR authority.','An unnecessary write capability creates avoidable consequences.','HR updates need a separately authorized process and deterministic controls.'),c('Read all shared folders so the assistant can find relevant context.','Broad context may include confidential records unrelated to onboarding.','Sensitive data can enter the answer even when no write tools exist.','Add sources only after purpose, access and retention review.'),c('Read approved onboarding sources; draft cited answers for review; stop on missing or conflicting policy.','This is a bounded objective with a clear failure path.','A reviewer owns the answer rather than the assistant creating policy.','Expand the scope only after a demonstrated need and access review.')],2),
q('practice-reliability-test','A draft answer is grammatical and cites a policy title. What additional check matters?','A title is not proof that the cited policy supports the answer.','Verify claims against their source before relying on output.',[
c('Check the actual policy passage and revision, then test missing and contradictory sources.','It verifies support and failure handling rather than appearance.','Unsupported answers can be withheld before confusing new staff.','Routine answers may later use lighter review after representative testing.'),c('Ask the assistant for a self-rated confidence and approve highly rated answers.','Self-rating needs calibration and cannot prove source support.','A confident unsupported answer may be approved.','Use confidence only as one calibrated signal with independent checks.'),c('Have a second assistant rewrite the answer more clearly.','Rewriting improves readability but may preserve the same unsupported claim.','The error becomes more persuasive.','Rewrite after factual and policy validation.')],0)],
discovery:[q('practice-discovery-next','A property manager wants automated tenant replies. You know there are 200 monthly messages but no request breakdown. What should the interview establish next?','Message count cannot distinguish routine notices from maintenance emergencies.','Find the action and escalation boundary before choosing a tool.',[
c('Budget, current inbox platform and whether tenants prefer email or text.','Implementation fit does not determine urgency or judgment.','The pilot may optimize the channel while missing emergencies.','Ask these after the service and escalation requirements are known.'),c('Request categories, emergency escalation, sensitive information and existing response ownership.','These distinguish safe routine help from consequential decisions.','The recommendation can keep emergency triage controlled.','An abbreviated interview is reasonable if a validated process already covers these points.'),c('Average message length and how long staff spend writing each response.','Labor measurement helps value but not safety or workflow scope.','A fast response system may send an inappropriate routine answer to an urgent request.','Time the work once categories and responsibilities are separated.')],1),
q('practice-discovery-validate','The manager estimates half the messages are routine. How should you validate that?','The estimate may overstate the share safely handled by a template.','Validate claims with a representative sample and an employee.',[
c('Use half as a conservative pilot assumption and cap the system at that volume.','A volume cap does not ensure the selected messages are routine.','The pilot may still handle the wrong cases.','Use the estimate only for an explicitly provisional screening calculation.'),c('Count existing templates as a proxy for routine message categories.','Template availability does not establish how often they fit incoming work.','A large template library may still leave most messages exceptional.','Use templates as one source when classifying actual messages.'),c('Review a time-bounded sample with staff and label routine, judgment-heavy and urgent messages.','It tests the work mix and reveals disagreements needing a rule.','The pilot boundary is evidence-led.','Expand the sample if seasonal or property-specific differences are material.')],2)],
diagnosis:[q('practice-diagnosis-cause','A law-office intake spends four minutes entering data but waits a day for conflict review. What should be tested first?','The delay occurs at a consequential review boundary, not primarily data entry.','Improve decision availability without bypassing professional authority.',[
c('Review queue ownership, required information and the timing of conflict decisions.','It tests the delay mechanism while preserving specialist review.','The firm may improve lead time through complete intake and scheduling.','Extraction can help later if active entry becomes a measured constraint.'),c('Use document extraction to halve the four-minute entry task.','This may save labor but does not explain the day of waiting.','The client may see little improvement in response time.','Prioritize it when entry volume and labor cost, rather than elapsed response, drive the objective.'),c('Generate a conflict-summary draft so reviewers can approve faster.','Summaries may help but review effort has not been shown to cause the wait.','A faster summary may sit in the same queue.','Use drafts if observation shows long review effort after information is complete.')],0),
q('practice-diagnosis-metric','Which baseline separates the hypothesized causes?','The workflow has both active work and queued review.','Measure each mechanism in its own units.',[
c('Total monthly payroll cost for all intake staff.','This aggregates unrelated tasks and cannot locate the wait.','A pilot cannot attribute the change to the targeted process.','Use payroll for financial realization after process measures exist.'),c('Elapsed time per stage, active review minutes, missing inputs and decision-owner availability.','The measures distinguish information gaps, effort and queuing.','The recommendation targets the right constraint.','Simplify the measures after the dominant mechanism is established.'),c('Number of completed conflict reviews per day.','Throughput alone does not show waiting or input quality.','Stable throughput can coexist with a growing queue.','Use throughput alongside queue-age and completeness measurements.')],1)],
current:[q('practice-current-scope','An invoice map starts at “approved invoice.” The complaint concerns slow approvals. What is wrong with that scope?','The map excludes the stage named in the business objective.','A useful map boundary contains the problem you are investigating.',[
c('It should instead start at payment so the financial output is visible.','This moves the scope farther from the approval constraint.','The upstream delay remains unexplained.','A payment map fits a separate objective about settlement.'),c('It needs more detailed payment-system fields.','Downstream detail cannot compensate for an omitted approval queue.','The consultant may design the wrong integration.','Add system fields after the relevant boundary is corrected.'),c('It must include receipt, completeness review, approval queue and decision ownership.','This brings the observed bottleneck into the map.','The team can validate where approval waits occur.','Keep an approved-invoice boundary only for a separately scoped payment process.')],2),
q('practice-current-exception','A map says incomplete invoices are “handled by finance.” What must be made explicit?','A department label does not define who acts, when or where the record waits.','Exceptions need an accountable route.',[
c('Named exception owner, return path, waiting state and criteria for resuming the normal flow.','These make recovery visible and testable.','Requests are less likely to disappear between handoffs.','A team queue can work if its ownership and service rules are explicit.'),c('A recommended automation platform for finance’s exception handling.','A tool cannot supply missing decision ownership.','Unowned records may remain unowned in a better interface.','Select tools after the recovery process is agreed.'),c('Average finance staffing cost and number of invoices handled.','Cost and volume aid prioritization but do not describe the exception path.','The redesign can undervalue lost or delayed records.','Use these figures alongside a documented route.')],0)],
future:[q('practice-future-change','A manufacturer revises a specification after a buyer drafted an order. Which control belongs in the future state?','The draft depends on a versioned specification and has not been released.','Tie authorization to the inputs it approved.',[
c('Update the attachment in storage and alert the supplier after release.','This keeps evidence but does not invalidate the obsolete draft.','The supplier can receive quantities for the wrong specification.','Use post-release supplier coordination when a prior order is already binding.'),c('Hold release, recalculate affected fields and reapprove the current revision.','This restores the link between specification, calculation and authority.','The order reflects the reviewed specification.','An approved impact rule may identify genuinely immaterial changes.'),c('Ask AI whether the revision looks material and reuse approval for low-risk changes.','Visual or textual plausibility cannot establish the authorized impact rule.','A seemingly small change can affect compatibility.','AI may highlight differences for a qualified reviewer, not decide approval reuse.')],1),
q('practice-future-failure','A release connector times out. What must the manual fallback verify first?','The first release may have succeeded despite the lost response.','Resolve transaction state before creating another side effect.',[
c('Whether the vendor accepts orders by email.','Channel capability does not show whether the order already exists.','A fallback email can duplicate a valid order.','Choose the fallback channel after checking current state.'),c('Whether the staff member has time to re-enter the order.','Capacity matters but not before purchase duplication is ruled out.','Fast manual recovery can create an expensive duplicate.','Use staffing checks when assigning an owned recovery queue.'),c('Whether the stable order ID already exists at the receiving system.','This distinguishes a failed request from a lost acknowledgment.','Manual recovery can continue without repeating the purchase.','If the receiving system cannot answer, escalate uncertainty to the authorized buyer.')],2)],
value:[q('practice-value-priority','A validated request form costs $600 and addresses $300 monthly rework. A forecasting pilot costs $5,000 and needs inventory cleanup. What is the best first engagement?','One benefit is supported and feasible; the larger option depends on unresolved data quality.','A quick win must deliver value while reducing uncertainty.',[
c('Forecasting, because purchasing errors could have the larger long-term cost.','Potential value is real but current feasibility and effect size are uncertain.','The client can pay for a model whose inputs remain unreliable.','Prioritize forecasting once clean stock data and a supported benefit estimate exist.'),c('Validated intake with rework measurement, while separately assessing forecasting data readiness.','It delivers an evidenced gain without abandoning a potentially valuable later option.','The team learns from a small investment and can decide on the larger case later.','Reverse priority if forecasting addresses an urgent, measured loss with reliable inputs.'),c('Run both pilots with one dashboard so the client sees a complete improvement program.','Parallel work increases cost and confounds outcome attribution.','The simpler fix may wait for the more complex project.','Parallel pilots can fit when resources, independent metrics and risk controls are already available.')],1),
q('practice-value-case','Which condition could make the form pilot unattractive?','Expected value assumes users submit complete requests through the new route.','Test realized value, not only nominal payback.',[
c('The form does not use AI and therefore offers limited long-term flexibility.','AI presence is not a business outcome.','A useful simple solution can be rejected for the wrong reason.','Flexibility matters only when variable needs materially affect value.'),c('Another platform has more sophisticated analytics features.','Additional features do not determine whether this pilot earns its cost.','The team may replace a feasible improvement with unnecessary scope.','Analytics matters when the agreed decisions require those measures.'),c('Low adoption and continuing clarification reduce net benefit below ongoing maintenance cost.','This directly challenges the realization assumption.','The owner should redesign, simplify or stop rather than claim savings.','Accept a low monetary return only when explicitly valued qualitative benefits justify it.')],2)],
delivery:[q('practice-delivery-accept','A logistics intake pilot is faster, but unusual shipments are not assigned. What should determine rollout?','Routine speed has improved while an exception has no owner.','Production acceptance includes owned recovery.',[
c('Assign an exception owner, test unusual shipments and confirm speed and error targets before release.','It closes the operational gap before expanding exposure.','The workflow can handle actual demand instead of just routine examples.','A narrow rollout is possible if unusual work remains in a clearly owned existing route.'),c('Roll out to routine shipments and ask teams to report unusual ones when they occur.','A bounded rollout is possible, but this wording does not define an exception route.','Unusual requests may wait until someone notices.','Use a subset rollout after explicit routing and responsibility are established.'),c('Extend staff training so employees know the pilot is for routine shipments.','Awareness helps but cannot assign responsibility for excluded work.','Teams may understand the limitation while still leaving requests unhandled.','Training is sufficient after the exception workflow is already defined.')],0),
q('practice-delivery-support','Which handoff makes the improvement maintainable?','The business needs ongoing operation after the consultant leaves.','Deliver ownership and acceptance evidence with the configuration.',[
c('A recording of the demo and the login credentials for the automation tool.','These show access and usage but not monitoring or recovery responsibilities.','A small failure can remain unnoticed until customers complain.','A demo supplements, rather than replaces, an operational handoff.'),c('Named monitoring/support owner, job aid, rollback route, scope limits and a post-pilot review date.','It establishes who detects and resolves failures and how success will be reviewed.','The improvement can remain controlled after handoff.','Lighter support fits a low-risk workflow with documented ownership.'),c('A technical diagram and monthly software-cost estimate.','Architecture and cost are useful but do not define day-to-day recovery.','The business may have documentation without an accountable operator.','Include these alongside the owner and recovery plan.')],1)]
};
